// Code generated by MockGen. DO NOT EDIT.
// Source: interfaces.go
//
// Generated by this command:
//
//	mockgen -source=interfaces.go -destination=mock_http.go -package=http
//

// Package http is a generated GoMock package.
package http

import (
	models "conduit/internal/models"
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockapplicationService is a mock of applicationService interface.
type MockapplicationService struct {
	ctrl     *gomock.Controller
	recorder *MockapplicationServiceMockRecorder
	isgomock struct{}
}

// MockapplicationServiceMockRecorder is the mock recorder for MockapplicationService.
type MockapplicationServiceMockRecorder struct {
	mock *MockapplicationService
}

// NewMockapplicationService creates a new mock instance.
func NewMockapplicationService(ctrl *gomock.Controller) *MockapplicationService {
	mock := &MockapplicationService{ctrl: ctrl}
	mock.recorder = &MockapplicationServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockapplicationService) EXPECT() *MockapplicationServiceMockRecorder {
	return m.recorder
}

// CreateArticle mocks base method.
func (m *MockapplicationService) CreateArticle(arg0 context.Context, arg1 models.NewArticleRequest) (*models.SingleArticleResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateArticle", arg0, arg1)
	ret0, _ := ret[0].(*models.SingleArticleResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateArticle indicates an expected call of CreateArticle.
func (mr *MockapplicationServiceMockRecorder) CreateArticle(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateArticle", reflect.TypeOf((*MockapplicationService)(nil).CreateArticle), arg0, arg1)
}

// CreateArticleComment mocks base method.
func (m *MockapplicationService) CreateArticleComment(arg0 context.Context, arg1 string, arg2 models.NewCommentRequest) (*models.SingleCommentResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateArticleComment", arg0, arg1, arg2)
	ret0, _ := ret[0].(*models.SingleCommentResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateArticleComment indicates an expected call of CreateArticleComment.
func (mr *MockapplicationServiceMockRecorder) CreateArticleComment(arg0, arg1, arg2 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateArticleComment", reflect.TypeOf((*MockapplicationService)(nil).CreateArticleComment), arg0, arg1, arg2)
}

// CreateArticleFavorite mocks base method.
func (m *MockapplicationService) CreateArticleFavorite(arg0 context.Context, arg1 string) (*models.SingleArticleResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateArticleFavorite", arg0, arg1)
	ret0, _ := ret[0].(*models.SingleArticleResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateArticleFavorite indicates an expected call of CreateArticleFavorite.
func (mr *MockapplicationServiceMockRecorder) CreateArticleFavorite(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateArticleFavorite", reflect.TypeOf((*MockapplicationService)(nil).CreateArticleFavorite), arg0, arg1)
}

// CreateUser mocks base method.
func (m *MockapplicationService) CreateUser(arg0 context.Context, arg1 models.NewUserRequest) (*models.UserResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateUser", arg0, arg1)
	ret0, _ := ret[0].(*models.UserResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateUser indicates an expected call of CreateUser.
func (mr *MockapplicationServiceMockRecorder) CreateUser(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateUser", reflect.TypeOf((*MockapplicationService)(nil).CreateUser), arg0, arg1)
}

// DeleteArticle mocks base method.
func (m *MockapplicationService) DeleteArticle(arg0 context.Context, arg1 string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteArticle", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteArticle indicates an expected call of DeleteArticle.
func (mr *MockapplicationServiceMockRecorder) DeleteArticle(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteArticle", reflect.TypeOf((*MockapplicationService)(nil).DeleteArticle), arg0, arg1)
}

// DeleteArticleComment mocks base method.
func (m *MockapplicationService) DeleteArticleComment(arg0 context.Context, arg1 string, arg2 int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteArticleComment", arg0, arg1, arg2)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteArticleComment indicates an expected call of DeleteArticleComment.
func (mr *MockapplicationServiceMockRecorder) DeleteArticleComment(arg0, arg1, arg2 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteArticleComment", reflect.TypeOf((*MockapplicationService)(nil).DeleteArticleComment), arg0, arg1, arg2)
}

// DeleteArticleFavorite mocks base method.
func (m *MockapplicationService) DeleteArticleFavorite(arg0 context.Context, arg1 string) (*models.SingleArticleResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteArticleFavorite", arg0, arg1)
	ret0, _ := ret[0].(*models.SingleArticleResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteArticleFavorite indicates an expected call of DeleteArticleFavorite.
func (mr *MockapplicationServiceMockRecorder) DeleteArticleFavorite(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteArticleFavorite", reflect.TypeOf((*MockapplicationService)(nil).DeleteArticleFavorite), arg0, arg1)
}

// FollowUserByUsername mocks base method.
func (m *MockapplicationService) FollowUserByUsername(arg0 context.Context, arg1 string) (*models.ProfileResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FollowUserByUsername", arg0, arg1)
	ret0, _ := ret[0].(*models.ProfileResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FollowUserByUsername indicates an expected call of FollowUserByUsername.
func (mr *MockapplicationServiceMockRecorder) FollowUserByUsername(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FollowUserByUsername", reflect.TypeOf((*MockapplicationService)(nil).FollowUserByUsername), arg0, arg1)
}

// GetArticle mocks base method.
func (m *MockapplicationService) GetArticle(arg0 context.Context, arg1 string) (*models.SingleArticleResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetArticle", arg0, arg1)
	ret0, _ := ret[0].(*models.SingleArticleResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetArticle indicates an expected call of GetArticle.
func (mr *MockapplicationServiceMockRecorder) GetArticle(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetArticle", reflect.TypeOf((*MockapplicationService)(nil).GetArticle), arg0, arg1)
}

// GetArticleComments mocks base method.
func (m *MockapplicationService) GetArticleComments(arg0 context.Context, arg1 string) (*models.MultipleCommentsResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetArticleComments", arg0, arg1)
	ret0, _ := ret[0].(*models.MultipleCommentsResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetArticleComments indicates an expected call of GetArticleComments.
func (mr *MockapplicationServiceMockRecorder) GetArticleComments(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetArticleComments", reflect.TypeOf((*MockapplicationService)(nil).GetArticleComments), arg0, arg1)
}

// GetArticles mocks base method.
func (m *MockapplicationService) GetArticles(arg0 context.Context, arg1 models.GetArticlesParams) (*models.MultipleArticlesResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetArticles", arg0, arg1)
	ret0, _ := ret[0].(*models.MultipleArticlesResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetArticles indicates an expected call of GetArticles.
func (mr *MockapplicationServiceMockRecorder) GetArticles(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetArticles", reflect.TypeOf((*MockapplicationService)(nil).GetArticles), arg0, arg1)
}

// GetArticlesFeed mocks base method.
func (m *MockapplicationService) GetArticlesFeed(arg0 context.Context, arg1 models.GetArticlesFeedParams) (*models.MultipleArticlesResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetArticlesFeed", arg0, arg1)
	ret0, _ := ret[0].(*models.MultipleArticlesResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetArticlesFeed indicates an expected call of GetArticlesFeed.
func (mr *MockapplicationServiceMockRecorder) GetArticlesFeed(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetArticlesFeed", reflect.TypeOf((*MockapplicationService)(nil).GetArticlesFeed), arg0, arg1)
}

// GetCurrentUser mocks base method.
func (m *MockapplicationService) GetCurrentUser(arg0 context.Context) (*models.UserResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCurrentUser", arg0)
	ret0, _ := ret[0].(*models.UserResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCurrentUser indicates an expected call of GetCurrentUser.
func (mr *MockapplicationServiceMockRecorder) GetCurrentUser(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCurrentUser", reflect.TypeOf((*MockapplicationService)(nil).GetCurrentUser), arg0)
}

// GetProfileByUsername mocks base method.
func (m *MockapplicationService) GetProfileByUsername(arg0 context.Context, arg1 string) (*models.ProfileResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetProfileByUsername", arg0, arg1)
	ret0, _ := ret[0].(*models.ProfileResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetProfileByUsername indicates an expected call of GetProfileByUsername.
func (mr *MockapplicationServiceMockRecorder) GetProfileByUsername(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetProfileByUsername", reflect.TypeOf((*MockapplicationService)(nil).GetProfileByUsername), arg0, arg1)
}

// GetTags mocks base method.
func (m *MockapplicationService) GetTags(arg0 context.Context) (*models.TagsResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTags", arg0)
	ret0, _ := ret[0].(*models.TagsResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTags indicates an expected call of GetTags.
func (mr *MockapplicationServiceMockRecorder) GetTags(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTags", reflect.TypeOf((*MockapplicationService)(nil).GetTags), arg0)
}

// Login mocks base method.
func (m *MockapplicationService) Login(arg0 context.Context, arg1 models.LoginUserRequest) (*models.UserResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Login", arg0, arg1)
	ret0, _ := ret[0].(*models.UserResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Login indicates an expected call of Login.
func (mr *MockapplicationServiceMockRecorder) Login(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Login", reflect.TypeOf((*MockapplicationService)(nil).Login), arg0, arg1)
}

// UnfollowUserByUsername mocks base method.
func (m *MockapplicationService) UnfollowUserByUsername(arg0 context.Context, arg1 string) (*models.ProfileResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UnfollowUserByUsername", arg0, arg1)
	ret0, _ := ret[0].(*models.ProfileResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UnfollowUserByUsername indicates an expected call of UnfollowUserByUsername.
func (mr *MockapplicationServiceMockRecorder) UnfollowUserByUsername(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UnfollowUserByUsername", reflect.TypeOf((*MockapplicationService)(nil).UnfollowUserByUsername), arg0, arg1)
}

// UpdateArticle mocks base method.
func (m *MockapplicationService) UpdateArticle(arg0 context.Context, arg1 string, arg2 models.UpdateArticleRequest) (*models.SingleArticleResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateArticle", arg0, arg1, arg2)
	ret0, _ := ret[0].(*models.SingleArticleResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateArticle indicates an expected call of UpdateArticle.
func (mr *MockapplicationServiceMockRecorder) UpdateArticle(arg0, arg1, arg2 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateArticle", reflect.TypeOf((*MockapplicationService)(nil).UpdateArticle), arg0, arg1, arg2)
}

// UpdateCurrentUser mocks base method.
func (m *MockapplicationService) UpdateCurrentUser(arg0 context.Context, arg1 *models.UpdateUserRequest) (*models.UserResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateCurrentUser", arg0, arg1)
	ret0, _ := ret[0].(*models.UserResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateCurrentUser indicates an expected call of UpdateCurrentUser.
func (mr *MockapplicationServiceMockRecorder) UpdateCurrentUser(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateCurrentUser", reflect.TypeOf((*MockapplicationService)(nil).UpdateCurrentUser), arg0, arg1)
}
