{{- /*
Simple gowrap template that builds an empty wrapper for any interface.
Usage example:
  gowrap gen -p your/module/pkg -i YourInterface -t ./gowrap/empty.tpl -o ./your_interface_empty_gen.go
*/ -}}

{{- $pkg := .Pkg.Name -}}
package {{$pkg}}

// {{.InterfaceName}}Wrapper is a no-op wrapper generated by gowrap.
type {{.InterfaceName}}Wrapper struct {
	decorated {{.Interface}}
}

// New{{.InterfaceName}}Wrapper returns an empty wrapper around the provided implementation.
func New{{.InterfaceName}}Wrapper(decorated {{.Interface}}) {{.Interface}} {
	return &{{.InterfaceName}}Wrapper{decorated: decorated}
}

{{- range .Methods}}
func (w *{{$.InterfaceName}}Wrapper) {{.Name}}({{Args .Params}}) {{ReturnTypes .Results}} {
	{{- if .Results}}
	{{- range $i, $r := .Results}}
	var r{{$i}} {{$r.Type}}
	{{- end}}
	return {{- range $i, $r := .Results}}{{if $i}}, {{end}}r{{$i}}{{- end}}
	{{- else}}
	return
	{{- end}}
}
{{- end}}
