// Code generated by MockGen. DO NOT EDIT.
// Source: interfaces.go
//
// Generated by this command:
//
//	mockgen -source=interfaces.go -destination=mock_articletag.go -package=articletag
//

// Package articletag is a generated GoMock package.
package articletag

import (
	postgres "conduit/internal/gen/postgres"
	context "context"
	reflect "reflect"

	pgtype "github.com/jackc/pgx/v5/pgtype"
	gomock "go.uber.org/mock/gomock"
)

// Mockrepository is a mock of repository interface.
type Mockrepository struct {
	ctrl     *gomock.Controller
	recorder *MockrepositoryMockRecorder
	isgomock struct{}
}

// MockrepositoryMockRecorder is the mock recorder for Mockrepository.
type MockrepositoryMockRecorder struct {
	mock *Mockrepository
}

// NewMockrepository creates a new mock instance.
func NewMockrepository(ctrl *gomock.Controller) *Mockrepository {
	mock := &Mockrepository{ctrl: ctrl}
	mock.recorder = &MockrepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *Mockrepository) EXPECT() *MockrepositoryMockRecorder {
	return m.recorder
}

// ListArticleIDsByTagID mocks base method.
func (m *Mockrepository) ListArticleIDsByTagID(arg0 context.Context, arg1 pgtype.UUID) ([]pgtype.UUID, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListArticleIDsByTagID", arg0, arg1)
	ret0, _ := ret[0].([]pgtype.UUID)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListArticleIDsByTagID indicates an expected call of ListArticleIDsByTagID.
func (mr *MockrepositoryMockRecorder) ListArticleIDsByTagID(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListArticleIDsByTagID", reflect.TypeOf((*Mockrepository)(nil).ListArticleIDsByTagID), arg0, arg1)
}

// ListArticleTagRelationsByArticleIDs mocks base method.
func (m *Mockrepository) ListArticleTagRelationsByArticleIDs(arg0 context.Context, arg1 []pgtype.UUID) ([]postgres.ListArticleTagRelationsByArticleIDsRow, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListArticleTagRelationsByArticleIDs", arg0, arg1)
	ret0, _ := ret[0].([]postgres.ListArticleTagRelationsByArticleIDsRow)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListArticleTagRelationsByArticleIDs indicates an expected call of ListArticleTagRelationsByArticleIDs.
func (mr *MockrepositoryMockRecorder) ListArticleTagRelationsByArticleIDs(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListArticleTagRelationsByArticleIDs", reflect.TypeOf((*Mockrepository)(nil).ListArticleTagRelationsByArticleIDs), arg0, arg1)
}
