// Code generated by MockGen. DO NOT EDIT.
// Source: service.go
//
// Generated by this command:
//
//	mockgen -source=service.go -destination=mock_gateway_test.go -package=gateway
//

// Package gateway is a generated GoMock package.
package gateway

import (
	models "conduit/internal/models"
	auth "conduit/internal/service/auth"
	authgrpc "conduit/internal/transport/grpc/auth"
	profile "conduit/internal/transport/grpc/profile"
	context "context"
	reflect "reflect"

	uuid "github.com/google/uuid"
	gomock "go.uber.org/mock/gomock"
)

// MockauthClient is a mock of authClient interface.
type MockauthClient struct {
	ctrl     *gomock.Controller
	recorder *MockauthClientMockRecorder
	isgomock struct{}
}

// MockauthClientMockRecorder is the mock recorder for MockauthClient.
type MockauthClientMockRecorder struct {
	mock *MockauthClient
}

// NewMockauthClient creates a new mock instance.
func NewMockauthClient(ctrl *gomock.Controller) *MockauthClient {
	mock := &MockauthClient{ctrl: ctrl}
	mock.recorder = &MockauthClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockauthClient) EXPECT() *MockauthClientMockRecorder {
	return m.recorder
}

// DeleteAccount mocks base method.
func (m *MockauthClient) DeleteAccount(arg0 context.Context, arg1 uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteAccount", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteAccount indicates an expected call of DeleteAccount.
func (mr *MockauthClientMockRecorder) DeleteAccount(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteAccount", reflect.TypeOf((*MockauthClient)(nil).DeleteAccount), arg0, arg1)
}

// GetAccount mocks base method.
func (m *MockauthClient) GetAccount(arg0 context.Context, arg1 uuid.UUID) (*auth.Account, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAccount", arg0, arg1)
	ret0, _ := ret[0].(*auth.Account)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAccount indicates an expected call of GetAccount.
func (mr *MockauthClientMockRecorder) GetAccount(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAccount", reflect.TypeOf((*MockauthClient)(nil).GetAccount), arg0, arg1)
}

// Login mocks base method.
func (m *MockauthClient) Login(arg0 context.Context, arg1, arg2 string) (*authgrpc.Result, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Login", arg0, arg1, arg2)
	ret0, _ := ret[0].(*authgrpc.Result)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Login indicates an expected call of Login.
func (mr *MockauthClientMockRecorder) Login(arg0, arg1, arg2 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Login", reflect.TypeOf((*MockauthClient)(nil).Login), arg0, arg1, arg2)
}

// Refresh mocks base method.
func (m *MockauthClient) Refresh(arg0 context.Context, arg1, arg2 string) (*authgrpc.Result, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Refresh", arg0, arg1, arg2)
	ret0, _ := ret[0].(*authgrpc.Result)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Refresh indicates an expected call of Refresh.
func (mr *MockauthClientMockRecorder) Refresh(arg0, arg1, arg2 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Refresh", reflect.TypeOf((*MockauthClient)(nil).Refresh), arg0, arg1, arg2)
}

// Register mocks base method.
func (m *MockauthClient) Register(arg0 context.Context, arg1, arg2, arg3 string) (*authgrpc.Result, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Register", arg0, arg1, arg2, arg3)
	ret0, _ := ret[0].(*authgrpc.Result)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Register indicates an expected call of Register.
func (mr *MockauthClientMockRecorder) Register(arg0, arg1, arg2, arg3 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Register", reflect.TypeOf((*MockauthClient)(nil).Register), arg0, arg1, arg2, arg3)
}

// UpdateCredentials mocks base method.
func (m *MockauthClient) UpdateCredentials(arg0 context.Context, arg1 uuid.UUID, arg2, arg3 *string) (*auth.Account, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateCredentials", arg0, arg1, arg2, arg3)
	ret0, _ := ret[0].(*auth.Account)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateCredentials indicates an expected call of UpdateCredentials.
func (mr *MockauthClientMockRecorder) UpdateCredentials(arg0, arg1, arg2, arg3 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateCredentials", reflect.TypeOf((*MockauthClient)(nil).UpdateCredentials), arg0, arg1, arg2, arg3)
}

// ValidateAccessToken mocks base method.
func (m *MockauthClient) ValidateAccessToken(arg0 context.Context, arg1 string) (*auth.TokenClaims, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ValidateAccessToken", arg0, arg1)
	ret0, _ := ret[0].(*auth.TokenClaims)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ValidateAccessToken indicates an expected call of ValidateAccessToken.
func (mr *MockauthClientMockRecorder) ValidateAccessToken(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ValidateAccessToken", reflect.TypeOf((*MockauthClient)(nil).ValidateAccessToken), arg0, arg1)
}

// MockprofileClient is a mock of profileClient interface.
type MockprofileClient struct {
	ctrl     *gomock.Controller
	recorder *MockprofileClientMockRecorder
	isgomock struct{}
}

// MockprofileClientMockRecorder is the mock recorder for MockprofileClient.
type MockprofileClientMockRecorder struct {
	mock *MockprofileClient
}

// NewMockprofileClient creates a new mock instance.
func NewMockprofileClient(ctrl *gomock.Controller) *MockprofileClient {
	mock := &MockprofileClient{ctrl: ctrl}
	mock.recorder = &MockprofileClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockprofileClient) EXPECT() *MockprofileClientMockRecorder {
	return m.recorder
}

// CreateProfile mocks base method.
func (m *MockprofileClient) CreateProfile(arg0 context.Context, arg1 uuid.UUID, arg2 string) (models.Profile, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateProfile", arg0, arg1, arg2)
	ret0, _ := ret[0].(models.Profile)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateProfile indicates an expected call of CreateProfile.
func (mr *MockprofileClientMockRecorder) CreateProfile(arg0, arg1, arg2 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateProfile", reflect.TypeOf((*MockprofileClient)(nil).CreateProfile), arg0, arg1, arg2)
}

// GetProfile mocks base method.
func (m *MockprofileClient) GetProfile(arg0 context.Context, arg1 uuid.UUID) (models.Profile, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetProfile", arg0, arg1)
	ret0, _ := ret[0].(models.Profile)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetProfile indicates an expected call of GetProfile.
func (mr *MockprofileClientMockRecorder) GetProfile(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetProfile", reflect.TypeOf((*MockprofileClient)(nil).GetProfile), arg0, arg1)
}

// GetProfileByUsername mocks base method.
func (m *MockprofileClient) GetProfileByUsername(arg0 context.Context, arg1 string) (models.Profile, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetProfileByUsername", arg0, arg1)
	ret0, _ := ret[0].(models.Profile)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetProfileByUsername indicates an expected call of GetProfileByUsername.
func (mr *MockprofileClientMockRecorder) GetProfileByUsername(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetProfileByUsername", reflect.TypeOf((*MockprofileClient)(nil).GetProfileByUsername), arg0, arg1)
}

// GetProfileSnapshot mocks base method.
func (m *MockprofileClient) GetProfileSnapshot(arg0 context.Context, arg1 uuid.UUID) (profile.Snapshot, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetProfileSnapshot", arg0, arg1)
	ret0, _ := ret[0].(profile.Snapshot)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetProfileSnapshot indicates an expected call of GetProfileSnapshot.
func (mr *MockprofileClientMockRecorder) GetProfileSnapshot(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetProfileSnapshot", reflect.TypeOf((*MockprofileClient)(nil).GetProfileSnapshot), arg0, arg1)
}

// UpdateProfile mocks base method.
func (m *MockprofileClient) UpdateProfile(arg0 context.Context, arg1 uuid.UUID, arg2 profile.Update) (models.Profile, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateProfile", arg0, arg1, arg2)
	ret0, _ := ret[0].(models.Profile)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateProfile indicates an expected call of UpdateProfile.
func (mr *MockprofileClientMockRecorder) UpdateProfile(arg0, arg1, arg2 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateProfile", reflect.TypeOf((*MockprofileClient)(nil).UpdateProfile), arg0, arg1, arg2)
}

// MocksubscriptionsClient is a mock of subscriptionsClient interface.
type MocksubscriptionsClient struct {
	ctrl     *gomock.Controller
	recorder *MocksubscriptionsClientMockRecorder
	isgomock struct{}
}

// MocksubscriptionsClientMockRecorder is the mock recorder for MocksubscriptionsClient.
type MocksubscriptionsClientMockRecorder struct {
	mock *MocksubscriptionsClient
}

// NewMocksubscriptionsClient creates a new mock instance.
func NewMocksubscriptionsClient(ctrl *gomock.Controller) *MocksubscriptionsClient {
	mock := &MocksubscriptionsClient{ctrl: ctrl}
	mock.recorder = &MocksubscriptionsClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MocksubscriptionsClient) EXPECT() *MocksubscriptionsClientMockRecorder {
	return m.recorder
}

// Follow mocks base method.
func (m *MocksubscriptionsClient) Follow(arg0 context.Context, arg1, arg2 uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Follow", arg0, arg1, arg2)
	ret0, _ := ret[0].(error)
	return ret0
}

// Follow indicates an expected call of Follow.
func (mr *MocksubscriptionsClientMockRecorder) Follow(arg0, arg1, arg2 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Follow", reflect.TypeOf((*MocksubscriptionsClient)(nil).Follow), arg0, arg1, arg2)
}

// IsFollowing mocks base method.
func (m *MocksubscriptionsClient) IsFollowing(arg0 context.Context, arg1, arg2 uuid.UUID) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsFollowing", arg0, arg1, arg2)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// IsFollowing indicates an expected call of IsFollowing.
func (mr *MocksubscriptionsClientMockRecorder) IsFollowing(arg0, arg1, arg2 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsFollowing", reflect.TypeOf((*MocksubscriptionsClient)(nil).IsFollowing), arg0, arg1, arg2)
}

// Unfollow mocks base method.
func (m *MocksubscriptionsClient) Unfollow(arg0 context.Context, arg1, arg2 uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Unfollow", arg0, arg1, arg2)
	ret0, _ := ret[0].(error)
	return ret0
}

// Unfollow indicates an expected call of Unfollow.
func (mr *MocksubscriptionsClientMockRecorder) Unfollow(arg0, arg1, arg2 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Unfollow", reflect.TypeOf((*MocksubscriptionsClient)(nil).Unfollow), arg0, arg1, arg2)
}

// MockarticleClient is a mock of articleClient interface.
type MockarticleClient struct {
	ctrl     *gomock.Controller
	recorder *MockarticleClientMockRecorder
	isgomock struct{}
}

// MockarticleClientMockRecorder is the mock recorder for MockarticleClient.
type MockarticleClientMockRecorder struct {
	mock *MockarticleClient
}

// NewMockarticleClient creates a new mock instance.
func NewMockarticleClient(ctrl *gomock.Controller) *MockarticleClient {
	mock := &MockarticleClient{ctrl: ctrl}
	mock.recorder = &MockarticleClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockarticleClient) EXPECT() *MockarticleClientMockRecorder {
	return m.recorder
}

// CreateArticle mocks base method.
func (m *MockarticleClient) CreateArticle(arg0 context.Context, arg1 models.NewArticleRequest) (*models.SingleArticleResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateArticle", arg0, arg1)
	ret0, _ := ret[0].(*models.SingleArticleResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateArticle indicates an expected call of CreateArticle.
func (mr *MockarticleClientMockRecorder) CreateArticle(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateArticle", reflect.TypeOf((*MockarticleClient)(nil).CreateArticle), arg0, arg1)
}

// CreateArticleFavorite mocks base method.
func (m *MockarticleClient) CreateArticleFavorite(arg0 context.Context, arg1 string) (*models.SingleArticleResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateArticleFavorite", arg0, arg1)
	ret0, _ := ret[0].(*models.SingleArticleResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateArticleFavorite indicates an expected call of CreateArticleFavorite.
func (mr *MockarticleClientMockRecorder) CreateArticleFavorite(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateArticleFavorite", reflect.TypeOf((*MockarticleClient)(nil).CreateArticleFavorite), arg0, arg1)
}

// DeleteArticle mocks base method.
func (m *MockarticleClient) DeleteArticle(arg0 context.Context, arg1 string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteArticle", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteArticle indicates an expected call of DeleteArticle.
func (mr *MockarticleClientMockRecorder) DeleteArticle(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteArticle", reflect.TypeOf((*MockarticleClient)(nil).DeleteArticle), arg0, arg1)
}

// DeleteArticleFavorite mocks base method.
func (m *MockarticleClient) DeleteArticleFavorite(arg0 context.Context, arg1 string) (*models.SingleArticleResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteArticleFavorite", arg0, arg1)
	ret0, _ := ret[0].(*models.SingleArticleResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteArticleFavorite indicates an expected call of DeleteArticleFavorite.
func (mr *MockarticleClientMockRecorder) DeleteArticleFavorite(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteArticleFavorite", reflect.TypeOf((*MockarticleClient)(nil).DeleteArticleFavorite), arg0, arg1)
}

// GetArticle mocks base method.
func (m *MockarticleClient) GetArticle(arg0 context.Context, arg1 string) (*models.SingleArticleResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetArticle", arg0, arg1)
	ret0, _ := ret[0].(*models.SingleArticleResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetArticle indicates an expected call of GetArticle.
func (mr *MockarticleClientMockRecorder) GetArticle(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetArticle", reflect.TypeOf((*MockarticleClient)(nil).GetArticle), arg0, arg1)
}

// GetArticles mocks base method.
func (m *MockarticleClient) GetArticles(arg0 context.Context, arg1 models.GetArticlesParams) (*models.MultipleArticlesResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetArticles", arg0, arg1)
	ret0, _ := ret[0].(*models.MultipleArticlesResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetArticles indicates an expected call of GetArticles.
func (mr *MockarticleClientMockRecorder) GetArticles(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetArticles", reflect.TypeOf((*MockarticleClient)(nil).GetArticles), arg0, arg1)
}

// GetArticlesFeed mocks base method.
func (m *MockarticleClient) GetArticlesFeed(arg0 context.Context, arg1 models.GetArticlesFeedParams) (*models.MultipleArticlesResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetArticlesFeed", arg0, arg1)
	ret0, _ := ret[0].(*models.MultipleArticlesResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetArticlesFeed indicates an expected call of GetArticlesFeed.
func (mr *MockarticleClientMockRecorder) GetArticlesFeed(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetArticlesFeed", reflect.TypeOf((*MockarticleClient)(nil).GetArticlesFeed), arg0, arg1)
}

// GetTags mocks base method.
func (m *MockarticleClient) GetTags(arg0 context.Context) (*models.TagsResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTags", arg0)
	ret0, _ := ret[0].(*models.TagsResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTags indicates an expected call of GetTags.
func (mr *MockarticleClientMockRecorder) GetTags(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTags", reflect.TypeOf((*MockarticleClient)(nil).GetTags), arg0)
}

// UpdateArticle mocks base method.
func (m *MockarticleClient) UpdateArticle(arg0 context.Context, arg1 string, arg2 models.UpdateArticleRequest) (*models.SingleArticleResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateArticle", arg0, arg1, arg2)
	ret0, _ := ret[0].(*models.SingleArticleResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateArticle indicates an expected call of UpdateArticle.
func (mr *MockarticleClientMockRecorder) UpdateArticle(arg0, arg1, arg2 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateArticle", reflect.TypeOf((*MockarticleClient)(nil).UpdateArticle), arg0, arg1, arg2)
}

// MockcommentClient is a mock of commentClient interface.
type MockcommentClient struct {
	ctrl     *gomock.Controller
	recorder *MockcommentClientMockRecorder
	isgomock struct{}
}

// MockcommentClientMockRecorder is the mock recorder for MockcommentClient.
type MockcommentClientMockRecorder struct {
	mock *MockcommentClient
}

// NewMockcommentClient creates a new mock instance.
func NewMockcommentClient(ctrl *gomock.Controller) *MockcommentClient {
	mock := &MockcommentClient{ctrl: ctrl}
	mock.recorder = &MockcommentClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockcommentClient) EXPECT() *MockcommentClientMockRecorder {
	return m.recorder
}

// CreateArticleComment mocks base method.
func (m *MockcommentClient) CreateArticleComment(arg0 context.Context, arg1 string, arg2 models.NewCommentRequest) (*models.SingleCommentResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateArticleComment", arg0, arg1, arg2)
	ret0, _ := ret[0].(*models.SingleCommentResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateArticleComment indicates an expected call of CreateArticleComment.
func (mr *MockcommentClientMockRecorder) CreateArticleComment(arg0, arg1, arg2 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateArticleComment", reflect.TypeOf((*MockcommentClient)(nil).CreateArticleComment), arg0, arg1, arg2)
}

// DeleteArticleComment mocks base method.
func (m *MockcommentClient) DeleteArticleComment(arg0 context.Context, arg1 string, arg2 int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteArticleComment", arg0, arg1, arg2)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteArticleComment indicates an expected call of DeleteArticleComment.
func (mr *MockcommentClientMockRecorder) DeleteArticleComment(arg0, arg1, arg2 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteArticleComment", reflect.TypeOf((*MockcommentClient)(nil).DeleteArticleComment), arg0, arg1, arg2)
}

// GetArticleComments mocks base method.
func (m *MockcommentClient) GetArticleComments(arg0 context.Context, arg1 string) (*models.MultipleCommentsResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetArticleComments", arg0, arg1)
	ret0, _ := ret[0].(*models.MultipleCommentsResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetArticleComments indicates an expected call of GetArticleComments.
func (mr *MockcommentClientMockRecorder) GetArticleComments(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetArticleComments", reflect.TypeOf((*MockcommentClient)(nil).GetArticleComments), arg0, arg1)
}
