apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: conduit
resources:
  - ../../base
replicas:
  - name: gateway
    count: 1
  - name: auth
    count: 1
  - name: profile
    count: 1
  - name: posts
    count: 1
  - name: subscriptions
    count: 1
  - name: comments
    count: 1
  - name: subscriptions-outbox
    count: 1
  - name: posts-outbox
    count: 1
  - name: profile-outbox
    count: 1
patches:
  - path: delete-hpa.yaml
  - target:
      kind: Deployment
    patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/resources/requests
        value:
          cpu: 10m
          memory: 32Mi
