// Code generated by MockGen. DO NOT EDIT.
// Source: interfaces.go
//
// Generated by this command:
//
//	mockgen -source=interfaces.go -destination=mock_user.go -package=user
//

// Package user is a generated GoMock package.
package user

import (
	postgres "conduit/internal/gen/postgres"
	context "context"
	reflect "reflect"

	uuid "github.com/google/uuid"
	pgtype "github.com/jackc/pgx/v5/pgtype"
	gomock "go.uber.org/mock/gomock"
)

// Mockrepository is a mock of repository interface.
type Mockrepository struct {
	ctrl     *gomock.Controller
	recorder *MockrepositoryMockRecorder
	isgomock struct{}
}

// MockrepositoryMockRecorder is the mock recorder for Mockrepository.
type MockrepositoryMockRecorder struct {
	mock *Mockrepository
}

// NewMockrepository creates a new mock instance.
func NewMockrepository(ctrl *gomock.Controller) *Mockrepository {
	mock := &Mockrepository{ctrl: ctrl}
	mock.recorder = &MockrepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *Mockrepository) EXPECT() *MockrepositoryMockRecorder {
	return m.recorder
}

// GetUserByID mocks base method.
func (m *Mockrepository) GetUserByID(arg0 context.Context, arg1 pgtype.UUID) (postgres.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserByID", arg0, arg1)
	ret0, _ := ret[0].(postgres.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserByID indicates an expected call of GetUserByID.
func (mr *MockrepositoryMockRecorder) GetUserByID(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserByID", reflect.TypeOf((*Mockrepository)(nil).GetUserByID), arg0, arg1)
}

// GetUserByUsername mocks base method.
func (m *Mockrepository) GetUserByUsername(arg0 context.Context, arg1 string) (postgres.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserByUsername", arg0, arg1)
	ret0, _ := ret[0].(postgres.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserByUsername indicates an expected call of GetUserByUsername.
func (mr *MockrepositoryMockRecorder) GetUserByUsername(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserByUsername", reflect.TypeOf((*Mockrepository)(nil).GetUserByUsername), arg0, arg1)
}

// GetUserIDByUsername mocks base method.
func (m *Mockrepository) GetUserIDByUsername(arg0 context.Context, arg1 string) (pgtype.UUID, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserIDByUsername", arg0, arg1)
	ret0, _ := ret[0].(pgtype.UUID)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserIDByUsername indicates an expected call of GetUserIDByUsername.
func (mr *MockrepositoryMockRecorder) GetUserIDByUsername(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserIDByUsername", reflect.TypeOf((*Mockrepository)(nil).GetUserIDByUsername), arg0, arg1)
}

// ListProfilesByIDs mocks base method.
func (m *Mockrepository) ListProfilesByIDs(arg0 context.Context, arg1 []pgtype.UUID) ([]postgres.ListProfilesByIDsRow, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListProfilesByIDs", arg0, arg1)
	ret0, _ := ret[0].([]postgres.ListProfilesByIDsRow)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListProfilesByIDs indicates an expected call of ListProfilesByIDs.
func (mr *MockrepositoryMockRecorder) ListProfilesByIDs(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListProfilesByIDs", reflect.TypeOf((*Mockrepository)(nil).ListProfilesByIDs), arg0, arg1)
}

// UpdateUser mocks base method.
func (m *Mockrepository) UpdateUser(arg0 context.Context, arg1 postgres.UpdateUserParams) (postgres.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateUser", arg0, arg1)
	ret0, _ := ret[0].(postgres.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateUser indicates an expected call of UpdateUser.
func (mr *MockrepositoryMockRecorder) UpdateUser(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateUser", reflect.TypeOf((*Mockrepository)(nil).UpdateUser), arg0, arg1)
}

// MockFollowService is a mock of FollowService interface.
type MockFollowService struct {
	ctrl     *gomock.Controller
	recorder *MockFollowServiceMockRecorder
	isgomock struct{}
}

// MockFollowServiceMockRecorder is the mock recorder for MockFollowService.
type MockFollowServiceMockRecorder struct {
	mock *MockFollowService
}

// NewMockFollowService creates a new mock instance.
func NewMockFollowService(ctrl *gomock.Controller) *MockFollowService {
	mock := &MockFollowService{ctrl: ctrl}
	mock.recorder = &MockFollowServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockFollowService) EXPECT() *MockFollowServiceMockRecorder {
	return m.recorder
}

// Follow mocks base method.
func (m *MockFollowService) Follow(arg0 context.Context, arg1, arg2 uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Follow", arg0, arg1, arg2)
	ret0, _ := ret[0].(error)
	return ret0
}

// Follow indicates an expected call of Follow.
func (mr *MockFollowServiceMockRecorder) Follow(arg0, arg1, arg2 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Follow", reflect.TypeOf((*MockFollowService)(nil).Follow), arg0, arg1, arg2)
}

// FollowingIDs mocks base method.
func (m *MockFollowService) FollowingIDs(arg0 context.Context, arg1 uuid.UUID, arg2 []uuid.UUID) (map[uuid.UUID]struct{}, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FollowingIDs", arg0, arg1, arg2)
	ret0, _ := ret[0].(map[uuid.UUID]struct{})
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FollowingIDs indicates an expected call of FollowingIDs.
func (mr *MockFollowServiceMockRecorder) FollowingIDs(arg0, arg1, arg2 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FollowingIDs", reflect.TypeOf((*MockFollowService)(nil).FollowingIDs), arg0, arg1, arg2)
}

// IsFollowing mocks base method.
func (m *MockFollowService) IsFollowing(arg0 context.Context, arg1, arg2 uuid.UUID) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsFollowing", arg0, arg1, arg2)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// IsFollowing indicates an expected call of IsFollowing.
func (mr *MockFollowServiceMockRecorder) IsFollowing(arg0, arg1, arg2 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsFollowing", reflect.TypeOf((*MockFollowService)(nil).IsFollowing), arg0, arg1, arg2)
}

// Unfollow mocks base method.
func (m *MockFollowService) Unfollow(arg0 context.Context, arg1, arg2 uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Unfollow", arg0, arg1, arg2)
	ret0, _ := ret[0].(error)
	return ret0
}

// Unfollow indicates an expected call of Unfollow.
func (mr *MockFollowServiceMockRecorder) Unfollow(arg0, arg1, arg2 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Unfollow", reflect.TypeOf((*MockFollowService)(nil).Unfollow), arg0, arg1, arg2)
}

// MockPasswordManager is a mock of PasswordManager interface.
type MockPasswordManager struct {
	ctrl     *gomock.Controller
	recorder *MockPasswordManagerMockRecorder
	isgomock struct{}
}

// MockPasswordManagerMockRecorder is the mock recorder for MockPasswordManager.
type MockPasswordManagerMockRecorder struct {
	mock *MockPasswordManager
}

// NewMockPasswordManager creates a new mock instance.
func NewMockPasswordManager(ctrl *gomock.Controller) *MockPasswordManager {
	mock := &MockPasswordManager{ctrl: ctrl}
	mock.recorder = &MockPasswordManagerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPasswordManager) EXPECT() *MockPasswordManagerMockRecorder {
	return m.recorder
}

// Hash mocks base method.
func (m *MockPasswordManager) Hash(arg0 string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Hash", arg0)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Hash indicates an expected call of Hash.
func (mr *MockPasswordManagerMockRecorder) Hash(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Hash", reflect.TypeOf((*MockPasswordManager)(nil).Hash), arg0)
}
