// Code generated by MockGen. DO NOT EDIT.
// Source: interfaces.go
//
// Generated by this command:
//
//	mockgen -source=interfaces.go -destination=mock_article.go -package=article
//

// Package article is a generated GoMock package.
package article

import (
	postgres "conduit/internal/gen/postgres"
	models "conduit/internal/models"
	context "context"
	reflect "reflect"

	uuid "github.com/google/uuid"
	pgtype "github.com/jackc/pgx/v5/pgtype"
	gomock "go.uber.org/mock/gomock"
)

// Mockrepository is a mock of repository interface.
type Mockrepository struct {
	ctrl     *gomock.Controller
	recorder *MockrepositoryMockRecorder
	isgomock struct{}
}

// MockrepositoryMockRecorder is the mock recorder for Mockrepository.
type MockrepositoryMockRecorder struct {
	mock *Mockrepository
}

// NewMockrepository creates a new mock instance.
func NewMockrepository(ctrl *gomock.Controller) *Mockrepository {
	mock := &Mockrepository{ctrl: ctrl}
	mock.recorder = &MockrepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *Mockrepository) EXPECT() *MockrepositoryMockRecorder {
	return m.recorder
}

// AttachTagsToArticle mocks base method.
func (m *Mockrepository) AttachTagsToArticle(arg0 context.Context, arg1 postgres.AttachTagsToArticleParams) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AttachTagsToArticle", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// AttachTagsToArticle indicates an expected call of AttachTagsToArticle.
func (mr *MockrepositoryMockRecorder) AttachTagsToArticle(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AttachTagsToArticle", reflect.TypeOf((*Mockrepository)(nil).AttachTagsToArticle), arg0, arg1)
}

// CountArticles mocks base method.
func (m *Mockrepository) CountArticles(arg0 context.Context, arg1 postgres.CountArticlesParams) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CountArticles", arg0, arg1)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CountArticles indicates an expected call of CountArticles.
func (mr *MockrepositoryMockRecorder) CountArticles(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CountArticles", reflect.TypeOf((*Mockrepository)(nil).CountArticles), arg0, arg1)
}

// CreateArticle mocks base method.
func (m *Mockrepository) CreateArticle(arg0 context.Context, arg1 postgres.CreateArticleParams) (pgtype.UUID, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateArticle", arg0, arg1)
	ret0, _ := ret[0].(pgtype.UUID)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateArticle indicates an expected call of CreateArticle.
func (mr *MockrepositoryMockRecorder) CreateArticle(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateArticle", reflect.TypeOf((*Mockrepository)(nil).CreateArticle), arg0, arg1)
}

// DeleteArticleBySlugAndAuthorID mocks base method.
func (m *Mockrepository) DeleteArticleBySlugAndAuthorID(arg0 context.Context, arg1 postgres.DeleteArticleBySlugAndAuthorIDParams) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteArticleBySlugAndAuthorID", arg0, arg1)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteArticleBySlugAndAuthorID indicates an expected call of DeleteArticleBySlugAndAuthorID.
func (mr *MockrepositoryMockRecorder) DeleteArticleBySlugAndAuthorID(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteArticleBySlugAndAuthorID", reflect.TypeOf((*Mockrepository)(nil).DeleteArticleBySlugAndAuthorID), arg0, arg1)
}

// DeleteArticleTags mocks base method.
func (m *Mockrepository) DeleteArticleTags(arg0 context.Context, arg1 pgtype.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteArticleTags", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteArticleTags indicates an expected call of DeleteArticleTags.
func (mr *MockrepositoryMockRecorder) DeleteArticleTags(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteArticleTags", reflect.TypeOf((*Mockrepository)(nil).DeleteArticleTags), arg0, arg1)
}

// GetArticleBySlug mocks base method.
func (m *Mockrepository) GetArticleBySlug(arg0 context.Context, arg1 string) (postgres.Article, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetArticleBySlug", arg0, arg1)
	ret0, _ := ret[0].(postgres.Article)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetArticleBySlug indicates an expected call of GetArticleBySlug.
func (mr *MockrepositoryMockRecorder) GetArticleBySlug(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetArticleBySlug", reflect.TypeOf((*Mockrepository)(nil).GetArticleBySlug), arg0, arg1)
}

// GetArticleIDBySlug mocks base method.
func (m *Mockrepository) GetArticleIDBySlug(arg0 context.Context, arg1 string) (pgtype.UUID, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetArticleIDBySlug", arg0, arg1)
	ret0, _ := ret[0].(pgtype.UUID)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetArticleIDBySlug indicates an expected call of GetArticleIDBySlug.
func (mr *MockrepositoryMockRecorder) GetArticleIDBySlug(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetArticleIDBySlug", reflect.TypeOf((*Mockrepository)(nil).GetArticleIDBySlug), arg0, arg1)
}

// ListArticles mocks base method.
func (m *Mockrepository) ListArticles(arg0 context.Context, arg1 postgres.ListArticlesParams) ([]postgres.Article, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListArticles", arg0, arg1)
	ret0, _ := ret[0].([]postgres.Article)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListArticles indicates an expected call of ListArticles.
func (mr *MockrepositoryMockRecorder) ListArticles(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListArticles", reflect.TypeOf((*Mockrepository)(nil).ListArticles), arg0, arg1)
}

// UpdateArticle mocks base method.
func (m *Mockrepository) UpdateArticle(arg0 context.Context, arg1 postgres.UpdateArticleParams) (pgtype.UUID, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateArticle", arg0, arg1)
	ret0, _ := ret[0].(pgtype.UUID)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateArticle indicates an expected call of UpdateArticle.
func (mr *MockrepositoryMockRecorder) UpdateArticle(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateArticle", reflect.TypeOf((*Mockrepository)(nil).UpdateArticle), arg0, arg1)
}

// UpsertTags mocks base method.
func (m *Mockrepository) UpsertTags(arg0 context.Context, arg1 postgres.UpsertTagsParams) ([]postgres.Tag, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpsertTags", arg0, arg1)
	ret0, _ := ret[0].([]postgres.Tag)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpsertTags indicates an expected call of UpsertTags.
func (mr *MockrepositoryMockRecorder) UpsertTags(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpsertTags", reflect.TypeOf((*Mockrepository)(nil).UpsertTags), arg0, arg1)
}

// Mocktransactions is a mock of transactions interface.
type Mocktransactions struct {
	ctrl     *gomock.Controller
	recorder *MocktransactionsMockRecorder
	isgomock struct{}
}

// MocktransactionsMockRecorder is the mock recorder for Mocktransactions.
type MocktransactionsMockRecorder struct {
	mock *Mocktransactions
}

// NewMocktransactions creates a new mock instance.
func NewMocktransactions(ctrl *gomock.Controller) *Mocktransactions {
	mock := &Mocktransactions{ctrl: ctrl}
	mock.recorder = &MocktransactionsMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *Mocktransactions) EXPECT() *MocktransactionsMockRecorder {
	return m.recorder
}

// WithTx mocks base method.
func (m *Mocktransactions) WithTx(arg0 context.Context, arg1 func(postgres.Querier) error) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "WithTx", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// WithTx indicates an expected call of WithTx.
func (mr *MocktransactionsMockRecorder) WithTx(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WithTx", reflect.TypeOf((*Mocktransactions)(nil).WithTx), arg0, arg1)
}

// MockUserService is a mock of UserService interface.
type MockUserService struct {
	ctrl     *gomock.Controller
	recorder *MockUserServiceMockRecorder
	isgomock struct{}
}

// MockUserServiceMockRecorder is the mock recorder for MockUserService.
type MockUserServiceMockRecorder struct {
	mock *MockUserService
}

// NewMockUserService creates a new mock instance.
func NewMockUserService(ctrl *gomock.Controller) *MockUserService {
	mock := &MockUserService{ctrl: ctrl}
	mock.recorder = &MockUserServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUserService) EXPECT() *MockUserServiceMockRecorder {
	return m.recorder
}

// IDByUsername mocks base method.
func (m *MockUserService) IDByUsername(arg0 context.Context, arg1 string) (uuid.UUID, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IDByUsername", arg0, arg1)
	ret0, _ := ret[0].(uuid.UUID)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// IDByUsername indicates an expected call of IDByUsername.
func (mr *MockUserServiceMockRecorder) IDByUsername(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IDByUsername", reflect.TypeOf((*MockUserService)(nil).IDByUsername), arg0, arg1)
}

// ProfilesByIDs mocks base method.
func (m *MockUserService) ProfilesByIDs(arg0 context.Context, arg1 []uuid.UUID) (map[uuid.UUID]models.Profile, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ProfilesByIDs", arg0, arg1)
	ret0, _ := ret[0].(map[uuid.UUID]models.Profile)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ProfilesByIDs indicates an expected call of ProfilesByIDs.
func (mr *MockUserServiceMockRecorder) ProfilesByIDs(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ProfilesByIDs", reflect.TypeOf((*MockUserService)(nil).ProfilesByIDs), arg0, arg1)
}

// MockTagService is a mock of TagService interface.
type MockTagService struct {
	ctrl     *gomock.Controller
	recorder *MockTagServiceMockRecorder
	isgomock struct{}
}

// MockTagServiceMockRecorder is the mock recorder for MockTagService.
type MockTagServiceMockRecorder struct {
	mock *MockTagService
}

// NewMockTagService creates a new mock instance.
func NewMockTagService(ctrl *gomock.Controller) *MockTagService {
	mock := &MockTagService{ctrl: ctrl}
	mock.recorder = &MockTagServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTagService) EXPECT() *MockTagServiceMockRecorder {
	return m.recorder
}

// IDByName mocks base method.
func (m *MockTagService) IDByName(arg0 context.Context, arg1 string) (uuid.UUID, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IDByName", arg0, arg1)
	ret0, _ := ret[0].(uuid.UUID)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// IDByName indicates an expected call of IDByName.
func (mr *MockTagServiceMockRecorder) IDByName(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IDByName", reflect.TypeOf((*MockTagService)(nil).IDByName), arg0, arg1)
}

// NamesByIDs mocks base method.
func (m *MockTagService) NamesByIDs(arg0 context.Context, arg1 []uuid.UUID) (map[uuid.UUID]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "NamesByIDs", arg0, arg1)
	ret0, _ := ret[0].(map[uuid.UUID]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// NamesByIDs indicates an expected call of NamesByIDs.
func (mr *MockTagServiceMockRecorder) NamesByIDs(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NamesByIDs", reflect.TypeOf((*MockTagService)(nil).NamesByIDs), arg0, arg1)
}

// MockArticleTagService is a mock of ArticleTagService interface.
type MockArticleTagService struct {
	ctrl     *gomock.Controller
	recorder *MockArticleTagServiceMockRecorder
	isgomock struct{}
}

// MockArticleTagServiceMockRecorder is the mock recorder for MockArticleTagService.
type MockArticleTagServiceMockRecorder struct {
	mock *MockArticleTagService
}

// NewMockArticleTagService creates a new mock instance.
func NewMockArticleTagService(ctrl *gomock.Controller) *MockArticleTagService {
	mock := &MockArticleTagService{ctrl: ctrl}
	mock.recorder = &MockArticleTagServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockArticleTagService) EXPECT() *MockArticleTagServiceMockRecorder {
	return m.recorder
}

// ArticleIDs mocks base method.
func (m *MockArticleTagService) ArticleIDs(arg0 context.Context, arg1 uuid.UUID) ([]uuid.UUID, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ArticleIDs", arg0, arg1)
	ret0, _ := ret[0].([]uuid.UUID)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ArticleIDs indicates an expected call of ArticleIDs.
func (mr *MockArticleTagServiceMockRecorder) ArticleIDs(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ArticleIDs", reflect.TypeOf((*MockArticleTagService)(nil).ArticleIDs), arg0, arg1)
}

// TagIDsByArticleIDs mocks base method.
func (m *MockArticleTagService) TagIDsByArticleIDs(arg0 context.Context, arg1 []uuid.UUID) (map[uuid.UUID][]uuid.UUID, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "TagIDsByArticleIDs", arg0, arg1)
	ret0, _ := ret[0].(map[uuid.UUID][]uuid.UUID)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// TagIDsByArticleIDs indicates an expected call of TagIDsByArticleIDs.
func (mr *MockArticleTagServiceMockRecorder) TagIDsByArticleIDs(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "TagIDsByArticleIDs", reflect.TypeOf((*MockArticleTagService)(nil).TagIDsByArticleIDs), arg0, arg1)
}

// MockFavoriteService is a mock of FavoriteService interface.
type MockFavoriteService struct {
	ctrl     *gomock.Controller
	recorder *MockFavoriteServiceMockRecorder
	isgomock struct{}
}

// MockFavoriteServiceMockRecorder is the mock recorder for MockFavoriteService.
type MockFavoriteServiceMockRecorder struct {
	mock *MockFavoriteService
}

// NewMockFavoriteService creates a new mock instance.
func NewMockFavoriteService(ctrl *gomock.Controller) *MockFavoriteService {
	mock := &MockFavoriteService{ctrl: ctrl}
	mock.recorder = &MockFavoriteServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockFavoriteService) EXPECT() *MockFavoriteServiceMockRecorder {
	return m.recorder
}

// Add mocks base method.
func (m *MockFavoriteService) Add(arg0 context.Context, arg1, arg2 uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Add", arg0, arg1, arg2)
	ret0, _ := ret[0].(error)
	return ret0
}

// Add indicates an expected call of Add.
func (mr *MockFavoriteServiceMockRecorder) Add(arg0, arg1, arg2 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Add", reflect.TypeOf((*MockFavoriteService)(nil).Add), arg0, arg1, arg2)
}

// ArticleIDsForUser mocks base method.
func (m *MockFavoriteService) ArticleIDsForUser(arg0 context.Context, arg1 uuid.UUID) ([]uuid.UUID, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ArticleIDsForUser", arg0, arg1)
	ret0, _ := ret[0].([]uuid.UUID)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ArticleIDsForUser indicates an expected call of ArticleIDsForUser.
func (mr *MockFavoriteServiceMockRecorder) ArticleIDsForUser(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ArticleIDsForUser", reflect.TypeOf((*MockFavoriteService)(nil).ArticleIDsForUser), arg0, arg1)
}

// CountsByArticleIDs mocks base method.
func (m *MockFavoriteService) CountsByArticleIDs(arg0 context.Context, arg1 []uuid.UUID) (map[uuid.UUID]int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CountsByArticleIDs", arg0, arg1)
	ret0, _ := ret[0].(map[uuid.UUID]int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CountsByArticleIDs indicates an expected call of CountsByArticleIDs.
func (mr *MockFavoriteServiceMockRecorder) CountsByArticleIDs(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CountsByArticleIDs", reflect.TypeOf((*MockFavoriteService)(nil).CountsByArticleIDs), arg0, arg1)
}

// FavoritedArticleIDs mocks base method.
func (m *MockFavoriteService) FavoritedArticleIDs(arg0 context.Context, arg1 uuid.UUID, arg2 []uuid.UUID) (map[uuid.UUID]struct{}, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FavoritedArticleIDs", arg0, arg1, arg2)
	ret0, _ := ret[0].(map[uuid.UUID]struct{})
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FavoritedArticleIDs indicates an expected call of FavoritedArticleIDs.
func (mr *MockFavoriteServiceMockRecorder) FavoritedArticleIDs(arg0, arg1, arg2 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FavoritedArticleIDs", reflect.TypeOf((*MockFavoriteService)(nil).FavoritedArticleIDs), arg0, arg1, arg2)
}

// Remove mocks base method.
func (m *MockFavoriteService) Remove(arg0 context.Context, arg1, arg2 uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Remove", arg0, arg1, arg2)
	ret0, _ := ret[0].(error)
	return ret0
}

// Remove indicates an expected call of Remove.
func (mr *MockFavoriteServiceMockRecorder) Remove(arg0, arg1, arg2 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Remove", reflect.TypeOf((*MockFavoriteService)(nil).Remove), arg0, arg1, arg2)
}

// MockFollowService is a mock of FollowService interface.
type MockFollowService struct {
	ctrl     *gomock.Controller
	recorder *MockFollowServiceMockRecorder
	isgomock struct{}
}

// MockFollowServiceMockRecorder is the mock recorder for MockFollowService.
type MockFollowServiceMockRecorder struct {
	mock *MockFollowService
}

// NewMockFollowService creates a new mock instance.
func NewMockFollowService(ctrl *gomock.Controller) *MockFollowService {
	mock := &MockFollowService{ctrl: ctrl}
	mock.recorder = &MockFollowServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockFollowService) EXPECT() *MockFollowServiceMockRecorder {
	return m.recorder
}

// FolloweeIDs mocks base method.
func (m *MockFollowService) FolloweeIDs(arg0 context.Context, arg1 uuid.UUID) ([]uuid.UUID, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FolloweeIDs", arg0, arg1)
	ret0, _ := ret[0].([]uuid.UUID)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FolloweeIDs indicates an expected call of FolloweeIDs.
func (mr *MockFollowServiceMockRecorder) FolloweeIDs(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FolloweeIDs", reflect.TypeOf((*MockFollowService)(nil).FolloweeIDs), arg0, arg1)
}
