// Code generated by MockGen. DO NOT EDIT.
// Source: interfaces.go
//
// Generated by this command:
//
//	mockgen -source=interfaces.go -destination=mock_tag.go -package=tag
//

// Package tag is a generated GoMock package.
package tag

import (
	postgres "conduit/internal/gen/postgres"
	context "context"
	reflect "reflect"

	pgtype "github.com/jackc/pgx/v5/pgtype"
	gomock "go.uber.org/mock/gomock"
)

// Mockrepository is a mock of repository interface.
type Mockrepository struct {
	ctrl     *gomock.Controller
	recorder *MockrepositoryMockRecorder
	isgomock struct{}
}

// MockrepositoryMockRecorder is the mock recorder for Mockrepository.
type MockrepositoryMockRecorder struct {
	mock *Mockrepository
}

// NewMockrepository creates a new mock instance.
func NewMockrepository(ctrl *gomock.Controller) *Mockrepository {
	mock := &Mockrepository{ctrl: ctrl}
	mock.recorder = &MockrepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *Mockrepository) EXPECT() *MockrepositoryMockRecorder {
	return m.recorder
}

// GetTagIDByName mocks base method.
func (m *Mockrepository) GetTagIDByName(arg0 context.Context, arg1 string) (pgtype.UUID, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTagIDByName", arg0, arg1)
	ret0, _ := ret[0].(pgtype.UUID)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTagIDByName indicates an expected call of GetTagIDByName.
func (mr *MockrepositoryMockRecorder) GetTagIDByName(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTagIDByName", reflect.TypeOf((*Mockrepository)(nil).GetTagIDByName), arg0, arg1)
}

// ListTags mocks base method.
func (m *Mockrepository) ListTags(arg0 context.Context) ([]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListTags", arg0)
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListTags indicates an expected call of ListTags.
func (mr *MockrepositoryMockRecorder) ListTags(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListTags", reflect.TypeOf((*Mockrepository)(nil).ListTags), arg0)
}

// ListTagsByIDs mocks base method.
func (m *Mockrepository) ListTagsByIDs(arg0 context.Context, arg1 []pgtype.UUID) ([]postgres.ListTagsByIDsRow, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListTagsByIDs", arg0, arg1)
	ret0, _ := ret[0].([]postgres.ListTagsByIDsRow)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListTagsByIDs indicates an expected call of ListTagsByIDs.
func (mr *MockrepositoryMockRecorder) ListTagsByIDs(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListTagsByIDs", reflect.TypeOf((*Mockrepository)(nil).ListTagsByIDs), arg0, arg1)
}
