// Code generated by MockGen. DO NOT EDIT.
// Source: conduit/internal/service/auth (interfaces: UserRepository,SessionRepository,TokenManagerIface,PasswordManagerIface)
//
// Generated by this command:
//
//	mockgen -destination=mock_auth.go -package=auth conduit/internal/service/auth UserRepository,SessionRepository,TokenManagerIface,PasswordManagerIface
//

// Package auth is a generated GoMock package.
package auth

import (
	postgres "conduit/internal/gen/postgres"
	context "context"
	reflect "reflect"

	pgtype "github.com/jackc/pgx/v5/pgtype"
	gomock "go.uber.org/mock/gomock"
)

// MockUserRepository is a mock of UserRepository interface.
type MockUserRepository struct {
	ctrl     *gomock.Controller
	recorder *MockUserRepositoryMockRecorder
	isgomock struct{}
}

// MockUserRepositoryMockRecorder is the mock recorder for MockUserRepository.
type MockUserRepositoryMockRecorder struct {
	mock *MockUserRepository
}

// NewMockUserRepository creates a new mock instance.
func NewMockUserRepository(ctrl *gomock.Controller) *MockUserRepository {
	mock := &MockUserRepository{ctrl: ctrl}
	mock.recorder = &MockUserRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUserRepository) EXPECT() *MockUserRepositoryMockRecorder {
	return m.recorder
}

// CreateUser mocks base method.
func (m *MockUserRepository) CreateUser(ctx context.Context, arg postgres.CreateUserParams) (postgres.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateUser", ctx, arg)
	ret0, _ := ret[0].(postgres.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateUser indicates an expected call of CreateUser.
func (mr *MockUserRepositoryMockRecorder) CreateUser(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateUser", reflect.TypeOf((*MockUserRepository)(nil).CreateUser), ctx, arg)
}

// GetUserByEmail mocks base method.
func (m *MockUserRepository) GetUserByEmail(ctx context.Context, email string) (postgres.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserByEmail", ctx, email)
	ret0, _ := ret[0].(postgres.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserByEmail indicates an expected call of GetUserByEmail.
func (mr *MockUserRepositoryMockRecorder) GetUserByEmail(ctx, email any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserByEmail", reflect.TypeOf((*MockUserRepository)(nil).GetUserByEmail), ctx, email)
}

// GetUserByID mocks base method.
func (m *MockUserRepository) GetUserByID(ctx context.Context, id pgtype.UUID) (postgres.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserByID", ctx, id)
	ret0, _ := ret[0].(postgres.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserByID indicates an expected call of GetUserByID.
func (mr *MockUserRepositoryMockRecorder) GetUserByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserByID", reflect.TypeOf((*MockUserRepository)(nil).GetUserByID), ctx, id)
}

// MockSessionRepository is a mock of SessionRepository interface.
type MockSessionRepository struct {
	ctrl     *gomock.Controller
	recorder *MockSessionRepositoryMockRecorder
	isgomock struct{}
}

// MockSessionRepositoryMockRecorder is the mock recorder for MockSessionRepository.
type MockSessionRepositoryMockRecorder struct {
	mock *MockSessionRepository
}

// NewMockSessionRepository creates a new mock instance.
func NewMockSessionRepository(ctrl *gomock.Controller) *MockSessionRepository {
	mock := &MockSessionRepository{ctrl: ctrl}
	mock.recorder = &MockSessionRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSessionRepository) EXPECT() *MockSessionRepositoryMockRecorder {
	return m.recorder
}

// CreateSession mocks base method.
func (m *MockSessionRepository) CreateSession(ctx context.Context, arg postgres.CreateSessionParams) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateSession", ctx, arg)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateSession indicates an expected call of CreateSession.
func (mr *MockSessionRepositoryMockRecorder) CreateSession(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateSession", reflect.TypeOf((*MockSessionRepository)(nil).CreateSession), ctx, arg)
}

// GetSessionByUserIDAndJWTIDAndRefreshToken mocks base method.
func (m *MockSessionRepository) GetSessionByUserIDAndJWTIDAndRefreshToken(ctx context.Context, arg postgres.GetSessionByUserIDAndJWTIDAndRefreshTokenParams) (postgres.Session, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSessionByUserIDAndJWTIDAndRefreshToken", ctx, arg)
	ret0, _ := ret[0].(postgres.Session)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSessionByUserIDAndJWTIDAndRefreshToken indicates an expected call of GetSessionByUserIDAndJWTIDAndRefreshToken.
func (mr *MockSessionRepositoryMockRecorder) GetSessionByUserIDAndJWTIDAndRefreshToken(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSessionByUserIDAndJWTIDAndRefreshToken", reflect.TypeOf((*MockSessionRepository)(nil).GetSessionByUserIDAndJWTIDAndRefreshToken), ctx, arg)
}

// RotateSession mocks base method.
func (m *MockSessionRepository) RotateSession(ctx context.Context, arg postgres.RotateSessionParams) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RotateSession", ctx, arg)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RotateSession indicates an expected call of RotateSession.
func (mr *MockSessionRepositoryMockRecorder) RotateSession(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RotateSession", reflect.TypeOf((*MockSessionRepository)(nil).RotateSession), ctx, arg)
}

// MockTokenManagerIface is a mock of TokenManagerIface interface.
type MockTokenManagerIface struct {
	ctrl     *gomock.Controller
	recorder *MockTokenManagerIfaceMockRecorder
	isgomock struct{}
}

// MockTokenManagerIfaceMockRecorder is the mock recorder for MockTokenManagerIface.
type MockTokenManagerIfaceMockRecorder struct {
	mock *MockTokenManagerIface
}

// NewMockTokenManagerIface creates a new mock instance.
func NewMockTokenManagerIface(ctrl *gomock.Controller) *MockTokenManagerIface {
	mock := &MockTokenManagerIface{ctrl: ctrl}
	mock.recorder = &MockTokenManagerIfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTokenManagerIface) EXPECT() *MockTokenManagerIfaceMockRecorder {
	return m.recorder
}

// GeneratePair mocks base method.
func (m *MockTokenManagerIface) GeneratePair(userID string) (*TokenPair, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GeneratePair", userID)
	ret0, _ := ret[0].(*TokenPair)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GeneratePair indicates an expected call of GeneratePair.
func (mr *MockTokenManagerIfaceMockRecorder) GeneratePair(userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GeneratePair", reflect.TypeOf((*MockTokenManagerIface)(nil).GeneratePair), userID)
}

// ParseIgnoringExpiry mocks base method.
func (m *MockTokenManagerIface) ParseIgnoringExpiry(tokenString string) (*TokenClaims, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ParseIgnoringExpiry", tokenString)
	ret0, _ := ret[0].(*TokenClaims)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ParseIgnoringExpiry indicates an expected call of ParseIgnoringExpiry.
func (mr *MockTokenManagerIfaceMockRecorder) ParseIgnoringExpiry(tokenString any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ParseIgnoringExpiry", reflect.TypeOf((*MockTokenManagerIface)(nil).ParseIgnoringExpiry), tokenString)
}

// ValidateAccessToken mocks base method.
func (m *MockTokenManagerIface) ValidateAccessToken(token string) (*TokenClaims, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ValidateAccessToken", token)
	ret0, _ := ret[0].(*TokenClaims)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ValidateAccessToken indicates an expected call of ValidateAccessToken.
func (mr *MockTokenManagerIfaceMockRecorder) ValidateAccessToken(token any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ValidateAccessToken", reflect.TypeOf((*MockTokenManagerIface)(nil).ValidateAccessToken), token)
}

// ValidateRefreshToken mocks base method.
func (m *MockTokenManagerIface) ValidateRefreshToken(token string) (*TokenClaims, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ValidateRefreshToken", token)
	ret0, _ := ret[0].(*TokenClaims)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ValidateRefreshToken indicates an expected call of ValidateRefreshToken.
func (mr *MockTokenManagerIfaceMockRecorder) ValidateRefreshToken(token any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ValidateRefreshToken", reflect.TypeOf((*MockTokenManagerIface)(nil).ValidateRefreshToken), token)
}

// MockPasswordManagerIface is a mock of PasswordManagerIface interface.
type MockPasswordManagerIface struct {
	ctrl     *gomock.Controller
	recorder *MockPasswordManagerIfaceMockRecorder
	isgomock struct{}
}

// MockPasswordManagerIfaceMockRecorder is the mock recorder for MockPasswordManagerIface.
type MockPasswordManagerIfaceMockRecorder struct {
	mock *MockPasswordManagerIface
}

// NewMockPasswordManagerIface creates a new mock instance.
func NewMockPasswordManagerIface(ctrl *gomock.Controller) *MockPasswordManagerIface {
	mock := &MockPasswordManagerIface{ctrl: ctrl}
	mock.recorder = &MockPasswordManagerIfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPasswordManagerIface) EXPECT() *MockPasswordManagerIfaceMockRecorder {
	return m.recorder
}

// Hash mocks base method.
func (m *MockPasswordManagerIface) Hash(password string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Hash", password)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Hash indicates an expected call of Hash.
func (mr *MockPasswordManagerIfaceMockRecorder) Hash(password any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Hash", reflect.TypeOf((*MockPasswordManagerIface)(nil).Hash), password)
}

// Verify mocks base method.
func (m *MockPasswordManagerIface) Verify(password, encodedHash string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Verify", password, encodedHash)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Verify indicates an expected call of Verify.
func (mr *MockPasswordManagerIfaceMockRecorder) Verify(password, encodedHash any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Verify", reflect.TypeOf((*MockPasswordManagerIface)(nil).Verify), password, encodedHash)
}
