// Code generated by MockGen. DO NOT EDIT.
// Source: interfaces.go
//
// Generated by this command:
//
//	mockgen -source=interfaces.go -destination=mock_middleware.go -package=middleware
//

// Package middleware is a generated GoMock package.
package middleware

import (
	auth "conduit/internal/service/auth"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MocktokenValidator is a mock of tokenValidator interface.
type MocktokenValidator struct {
	ctrl     *gomock.Controller
	recorder *MocktokenValidatorMockRecorder
	isgomock struct{}
}

// MocktokenValidatorMockRecorder is the mock recorder for MocktokenValidator.
type MocktokenValidatorMockRecorder struct {
	mock *MocktokenValidator
}

// NewMocktokenValidator creates a new mock instance.
func NewMocktokenValidator(ctrl *gomock.Controller) *MocktokenValidator {
	mock := &MocktokenValidator{ctrl: ctrl}
	mock.recorder = &MocktokenValidatorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MocktokenValidator) EXPECT() *MocktokenValidatorMockRecorder {
	return m.recorder
}

// ValidateAccessToken mocks base method.
func (m *MocktokenValidator) ValidateAccessToken(arg0 string) (*auth.TokenClaims, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ValidateAccessToken", arg0)
	ret0, _ := ret[0].(*auth.TokenClaims)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ValidateAccessToken indicates an expected call of ValidateAccessToken.
func (mr *MocktokenValidatorMockRecorder) ValidateAccessToken(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ValidateAccessToken", reflect.TypeOf((*MocktokenValidator)(nil).ValidateAccessToken), arg0)
}
