// Code generated by MockGen. DO NOT EDIT.
// Source: interfaces.go
//
// Generated by this command:
//
//	mockgen -source=interfaces.go -destination=mock_favorite.go -package=favorite
//

// Package favorite is a generated GoMock package.
package favorite

import (
	postgres "conduit/internal/gen/postgres"
	context "context"
	reflect "reflect"

	pgtype "github.com/jackc/pgx/v5/pgtype"
	gomock "go.uber.org/mock/gomock"
)

// Mockrepository is a mock of repository interface.
type Mockrepository struct {
	ctrl     *gomock.Controller
	recorder *MockrepositoryMockRecorder
	isgomock struct{}
}

// MockrepositoryMockRecorder is the mock recorder for Mockrepository.
type MockrepositoryMockRecorder struct {
	mock *Mockrepository
}

// NewMockrepository creates a new mock instance.
func NewMockrepository(ctrl *gomock.Controller) *Mockrepository {
	mock := &Mockrepository{ctrl: ctrl}
	mock.recorder = &MockrepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *Mockrepository) EXPECT() *MockrepositoryMockRecorder {
	return m.recorder
}

// CountFavoritesByArticleIDs mocks base method.
func (m *Mockrepository) CountFavoritesByArticleIDs(arg0 context.Context, arg1 []pgtype.UUID) ([]postgres.CountFavoritesByArticleIDsRow, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CountFavoritesByArticleIDs", arg0, arg1)
	ret0, _ := ret[0].([]postgres.CountFavoritesByArticleIDsRow)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CountFavoritesByArticleIDs indicates an expected call of CountFavoritesByArticleIDs.
func (mr *MockrepositoryMockRecorder) CountFavoritesByArticleIDs(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CountFavoritesByArticleIDs", reflect.TypeOf((*Mockrepository)(nil).CountFavoritesByArticleIDs), arg0, arg1)
}

// FavoriteArticle mocks base method.
func (m *Mockrepository) FavoriteArticle(arg0 context.Context, arg1 postgres.FavoriteArticleParams) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FavoriteArticle", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// FavoriteArticle indicates an expected call of FavoriteArticle.
func (mr *MockrepositoryMockRecorder) FavoriteArticle(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FavoriteArticle", reflect.TypeOf((*Mockrepository)(nil).FavoriteArticle), arg0, arg1)
}

// ListFavoriteArticleIDsByUserID mocks base method.
func (m *Mockrepository) ListFavoriteArticleIDsByUserID(arg0 context.Context, arg1 pgtype.UUID) ([]pgtype.UUID, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListFavoriteArticleIDsByUserID", arg0, arg1)
	ret0, _ := ret[0].([]pgtype.UUID)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListFavoriteArticleIDsByUserID indicates an expected call of ListFavoriteArticleIDsByUserID.
func (mr *MockrepositoryMockRecorder) ListFavoriteArticleIDsByUserID(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListFavoriteArticleIDsByUserID", reflect.TypeOf((*Mockrepository)(nil).ListFavoriteArticleIDsByUserID), arg0, arg1)
}

// ListFavoriteArticleIDsByUserIDAndArticleIDs mocks base method.
func (m *Mockrepository) ListFavoriteArticleIDsByUserIDAndArticleIDs(arg0 context.Context, arg1 postgres.ListFavoriteArticleIDsByUserIDAndArticleIDsParams) ([]pgtype.UUID, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListFavoriteArticleIDsByUserIDAndArticleIDs", arg0, arg1)
	ret0, _ := ret[0].([]pgtype.UUID)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListFavoriteArticleIDsByUserIDAndArticleIDs indicates an expected call of ListFavoriteArticleIDsByUserIDAndArticleIDs.
func (mr *MockrepositoryMockRecorder) ListFavoriteArticleIDsByUserIDAndArticleIDs(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListFavoriteArticleIDsByUserIDAndArticleIDs", reflect.TypeOf((*Mockrepository)(nil).ListFavoriteArticleIDsByUserIDAndArticleIDs), arg0, arg1)
}

// UnfavoriteArticle mocks base method.
func (m *Mockrepository) UnfavoriteArticle(arg0 context.Context, arg1 postgres.UnfavoriteArticleParams) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UnfavoriteArticle", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// UnfavoriteArticle indicates an expected call of UnfavoriteArticle.
func (mr *MockrepositoryMockRecorder) UnfavoriteArticle(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UnfavoriteArticle", reflect.TypeOf((*Mockrepository)(nil).UnfavoriteArticle), arg0, arg1)
}
