// Code generated by MockGen. DO NOT EDIT.
// Source: interfaces.go
//
// Generated by this command:
//
//	mockgen -source=interfaces.go -destination=mock_service.go -package=service
//

// Package service is a generated GoMock package.
package service

import (
	models "conduit/internal/models"
	auth "conduit/internal/service/auth"
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockarticleService is a mock of articleService interface.
type MockarticleService struct {
	ctrl     *gomock.Controller
	recorder *MockarticleServiceMockRecorder
	isgomock struct{}
}

// MockarticleServiceMockRecorder is the mock recorder for MockarticleService.
type MockarticleServiceMockRecorder struct {
	mock *MockarticleService
}

// NewMockarticleService creates a new mock instance.
func NewMockarticleService(ctrl *gomock.Controller) *MockarticleService {
	mock := &MockarticleService{ctrl: ctrl}
	mock.recorder = &MockarticleServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockarticleService) EXPECT() *MockarticleServiceMockRecorder {
	return m.recorder
}

// CreateArticle mocks base method.
func (m *MockarticleService) CreateArticle(arg0 context.Context, arg1 models.NewArticleRequest) (*models.SingleArticleResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateArticle", arg0, arg1)
	ret0, _ := ret[0].(*models.SingleArticleResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateArticle indicates an expected call of CreateArticle.
func (mr *MockarticleServiceMockRecorder) CreateArticle(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateArticle", reflect.TypeOf((*MockarticleService)(nil).CreateArticle), arg0, arg1)
}

// CreateArticleFavorite mocks base method.
func (m *MockarticleService) CreateArticleFavorite(arg0 context.Context, arg1 string) (*models.SingleArticleResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateArticleFavorite", arg0, arg1)
	ret0, _ := ret[0].(*models.SingleArticleResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateArticleFavorite indicates an expected call of CreateArticleFavorite.
func (mr *MockarticleServiceMockRecorder) CreateArticleFavorite(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateArticleFavorite", reflect.TypeOf((*MockarticleService)(nil).CreateArticleFavorite), arg0, arg1)
}

// DeleteArticle mocks base method.
func (m *MockarticleService) DeleteArticle(arg0 context.Context, arg1 string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteArticle", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteArticle indicates an expected call of DeleteArticle.
func (mr *MockarticleServiceMockRecorder) DeleteArticle(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteArticle", reflect.TypeOf((*MockarticleService)(nil).DeleteArticle), arg0, arg1)
}

// DeleteArticleFavorite mocks base method.
func (m *MockarticleService) DeleteArticleFavorite(arg0 context.Context, arg1 string) (*models.SingleArticleResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteArticleFavorite", arg0, arg1)
	ret0, _ := ret[0].(*models.SingleArticleResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteArticleFavorite indicates an expected call of DeleteArticleFavorite.
func (mr *MockarticleServiceMockRecorder) DeleteArticleFavorite(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteArticleFavorite", reflect.TypeOf((*MockarticleService)(nil).DeleteArticleFavorite), arg0, arg1)
}

// GetArticle mocks base method.
func (m *MockarticleService) GetArticle(arg0 context.Context, arg1 string) (*models.SingleArticleResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetArticle", arg0, arg1)
	ret0, _ := ret[0].(*models.SingleArticleResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetArticle indicates an expected call of GetArticle.
func (mr *MockarticleServiceMockRecorder) GetArticle(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetArticle", reflect.TypeOf((*MockarticleService)(nil).GetArticle), arg0, arg1)
}

// GetArticles mocks base method.
func (m *MockarticleService) GetArticles(arg0 context.Context, arg1 models.GetArticlesParams) (*models.MultipleArticlesResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetArticles", arg0, arg1)
	ret0, _ := ret[0].(*models.MultipleArticlesResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetArticles indicates an expected call of GetArticles.
func (mr *MockarticleServiceMockRecorder) GetArticles(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetArticles", reflect.TypeOf((*MockarticleService)(nil).GetArticles), arg0, arg1)
}

// GetArticlesFeed mocks base method.
func (m *MockarticleService) GetArticlesFeed(arg0 context.Context, arg1 models.GetArticlesFeedParams) (*models.MultipleArticlesResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetArticlesFeed", arg0, arg1)
	ret0, _ := ret[0].(*models.MultipleArticlesResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetArticlesFeed indicates an expected call of GetArticlesFeed.
func (mr *MockarticleServiceMockRecorder) GetArticlesFeed(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetArticlesFeed", reflect.TypeOf((*MockarticleService)(nil).GetArticlesFeed), arg0, arg1)
}

// UpdateArticle mocks base method.
func (m *MockarticleService) UpdateArticle(arg0 context.Context, arg1 string, arg2 models.UpdateArticleRequest) (*models.SingleArticleResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateArticle", arg0, arg1, arg2)
	ret0, _ := ret[0].(*models.SingleArticleResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateArticle indicates an expected call of UpdateArticle.
func (mr *MockarticleServiceMockRecorder) UpdateArticle(arg0, arg1, arg2 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateArticle", reflect.TypeOf((*MockarticleService)(nil).UpdateArticle), arg0, arg1, arg2)
}

// MockauthService is a mock of authService interface.
type MockauthService struct {
	ctrl     *gomock.Controller
	recorder *MockauthServiceMockRecorder
	isgomock struct{}
}

// MockauthServiceMockRecorder is the mock recorder for MockauthService.
type MockauthServiceMockRecorder struct {
	mock *MockauthService
}

// NewMockauthService creates a new mock instance.
func NewMockauthService(ctrl *gomock.Controller) *MockauthService {
	mock := &MockauthService{ctrl: ctrl}
	mock.recorder = &MockauthServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockauthService) EXPECT() *MockauthServiceMockRecorder {
	return m.recorder
}

// CreateUser mocks base method.
func (m *MockauthService) CreateUser(arg0 context.Context, arg1 models.NewUserRequest) (*models.UserResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateUser", arg0, arg1)
	ret0, _ := ret[0].(*models.UserResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateUser indicates an expected call of CreateUser.
func (mr *MockauthServiceMockRecorder) CreateUser(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateUser", reflect.TypeOf((*MockauthService)(nil).CreateUser), arg0, arg1)
}

// Login mocks base method.
func (m *MockauthService) Login(arg0 context.Context, arg1 models.LoginUserRequest) (*models.UserResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Login", arg0, arg1)
	ret0, _ := ret[0].(*models.UserResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Login indicates an expected call of Login.
func (mr *MockauthServiceMockRecorder) Login(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Login", reflect.TypeOf((*MockauthService)(nil).Login), arg0, arg1)
}

// RefreshToken mocks base method.
func (m *MockauthService) RefreshToken(arg0 context.Context, arg1, arg2 string) (*models.UserResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RefreshToken", arg0, arg1, arg2)
	ret0, _ := ret[0].(*models.UserResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RefreshToken indicates an expected call of RefreshToken.
func (mr *MockauthServiceMockRecorder) RefreshToken(arg0, arg1, arg2 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RefreshToken", reflect.TypeOf((*MockauthService)(nil).RefreshToken), arg0, arg1, arg2)
}

// ValidateAccessToken mocks base method.
func (m *MockauthService) ValidateAccessToken(arg0 string) (*auth.TokenClaims, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ValidateAccessToken", arg0)
	ret0, _ := ret[0].(*auth.TokenClaims)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ValidateAccessToken indicates an expected call of ValidateAccessToken.
func (mr *MockauthServiceMockRecorder) ValidateAccessToken(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ValidateAccessToken", reflect.TypeOf((*MockauthService)(nil).ValidateAccessToken), arg0)
}

// MockcommentService is a mock of commentService interface.
type MockcommentService struct {
	ctrl     *gomock.Controller
	recorder *MockcommentServiceMockRecorder
	isgomock struct{}
}

// MockcommentServiceMockRecorder is the mock recorder for MockcommentService.
type MockcommentServiceMockRecorder struct {
	mock *MockcommentService
}

// NewMockcommentService creates a new mock instance.
func NewMockcommentService(ctrl *gomock.Controller) *MockcommentService {
	mock := &MockcommentService{ctrl: ctrl}
	mock.recorder = &MockcommentServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockcommentService) EXPECT() *MockcommentServiceMockRecorder {
	return m.recorder
}

// CreateArticleComment mocks base method.
func (m *MockcommentService) CreateArticleComment(arg0 context.Context, arg1 string, arg2 models.NewCommentRequest) (*models.SingleCommentResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateArticleComment", arg0, arg1, arg2)
	ret0, _ := ret[0].(*models.SingleCommentResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateArticleComment indicates an expected call of CreateArticleComment.
func (mr *MockcommentServiceMockRecorder) CreateArticleComment(arg0, arg1, arg2 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateArticleComment", reflect.TypeOf((*MockcommentService)(nil).CreateArticleComment), arg0, arg1, arg2)
}

// DeleteArticleComment mocks base method.
func (m *MockcommentService) DeleteArticleComment(arg0 context.Context, arg1 string, arg2 int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteArticleComment", arg0, arg1, arg2)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteArticleComment indicates an expected call of DeleteArticleComment.
func (mr *MockcommentServiceMockRecorder) DeleteArticleComment(arg0, arg1, arg2 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteArticleComment", reflect.TypeOf((*MockcommentService)(nil).DeleteArticleComment), arg0, arg1, arg2)
}

// GetArticleComments mocks base method.
func (m *MockcommentService) GetArticleComments(arg0 context.Context, arg1 string) (*models.MultipleCommentsResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetArticleComments", arg0, arg1)
	ret0, _ := ret[0].(*models.MultipleCommentsResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetArticleComments indicates an expected call of GetArticleComments.
func (mr *MockcommentServiceMockRecorder) GetArticleComments(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetArticleComments", reflect.TypeOf((*MockcommentService)(nil).GetArticleComments), arg0, arg1)
}

// MocktagService is a mock of tagService interface.
type MocktagService struct {
	ctrl     *gomock.Controller
	recorder *MocktagServiceMockRecorder
	isgomock struct{}
}

// MocktagServiceMockRecorder is the mock recorder for MocktagService.
type MocktagServiceMockRecorder struct {
	mock *MocktagService
}

// NewMocktagService creates a new mock instance.
func NewMocktagService(ctrl *gomock.Controller) *MocktagService {
	mock := &MocktagService{ctrl: ctrl}
	mock.recorder = &MocktagServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MocktagService) EXPECT() *MocktagServiceMockRecorder {
	return m.recorder
}

// GetTags mocks base method.
func (m *MocktagService) GetTags(arg0 context.Context) (*models.TagsResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTags", arg0)
	ret0, _ := ret[0].(*models.TagsResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTags indicates an expected call of GetTags.
func (mr *MocktagServiceMockRecorder) GetTags(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTags", reflect.TypeOf((*MocktagService)(nil).GetTags), arg0)
}

// MockuserService is a mock of userService interface.
type MockuserService struct {
	ctrl     *gomock.Controller
	recorder *MockuserServiceMockRecorder
	isgomock struct{}
}

// MockuserServiceMockRecorder is the mock recorder for MockuserService.
type MockuserServiceMockRecorder struct {
	mock *MockuserService
}

// NewMockuserService creates a new mock instance.
func NewMockuserService(ctrl *gomock.Controller) *MockuserService {
	mock := &MockuserService{ctrl: ctrl}
	mock.recorder = &MockuserServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockuserService) EXPECT() *MockuserServiceMockRecorder {
	return m.recorder
}

// FollowUserByUsername mocks base method.
func (m *MockuserService) FollowUserByUsername(arg0 context.Context, arg1 string) (*models.ProfileResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FollowUserByUsername", arg0, arg1)
	ret0, _ := ret[0].(*models.ProfileResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FollowUserByUsername indicates an expected call of FollowUserByUsername.
func (mr *MockuserServiceMockRecorder) FollowUserByUsername(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FollowUserByUsername", reflect.TypeOf((*MockuserService)(nil).FollowUserByUsername), arg0, arg1)
}

// GetCurrentUser mocks base method.
func (m *MockuserService) GetCurrentUser(arg0 context.Context) (*models.UserResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCurrentUser", arg0)
	ret0, _ := ret[0].(*models.UserResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCurrentUser indicates an expected call of GetCurrentUser.
func (mr *MockuserServiceMockRecorder) GetCurrentUser(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCurrentUser", reflect.TypeOf((*MockuserService)(nil).GetCurrentUser), arg0)
}

// GetProfileByUsername mocks base method.
func (m *MockuserService) GetProfileByUsername(arg0 context.Context, arg1 string) (*models.ProfileResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetProfileByUsername", arg0, arg1)
	ret0, _ := ret[0].(*models.ProfileResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetProfileByUsername indicates an expected call of GetProfileByUsername.
func (mr *MockuserServiceMockRecorder) GetProfileByUsername(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetProfileByUsername", reflect.TypeOf((*MockuserService)(nil).GetProfileByUsername), arg0, arg1)
}

// UnfollowUserByUsername mocks base method.
func (m *MockuserService) UnfollowUserByUsername(arg0 context.Context, arg1 string) (*models.ProfileResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UnfollowUserByUsername", arg0, arg1)
	ret0, _ := ret[0].(*models.ProfileResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UnfollowUserByUsername indicates an expected call of UnfollowUserByUsername.
func (mr *MockuserServiceMockRecorder) UnfollowUserByUsername(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UnfollowUserByUsername", reflect.TypeOf((*MockuserService)(nil).UnfollowUserByUsername), arg0, arg1)
}

// UpdateCurrentUser mocks base method.
func (m *MockuserService) UpdateCurrentUser(arg0 context.Context, arg1 *models.UpdateUserRequest) (*models.UserResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateCurrentUser", arg0, arg1)
	ret0, _ := ret[0].(*models.UserResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateCurrentUser indicates an expected call of UpdateCurrentUser.
func (mr *MockuserServiceMockRecorder) UpdateCurrentUser(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateCurrentUser", reflect.TypeOf((*MockuserService)(nil).UpdateCurrentUser), arg0, arg1)
}
