// Code generated by MockGen. DO NOT EDIT.
// Source: interfaces.go
//
// Generated by this command:
//
//	mockgen -source=interfaces.go -destination=mock_follow.go -package=follow
//

// Package follow is a generated GoMock package.
package follow

import (
	postgres "conduit/internal/gen/postgres"
	context "context"
	reflect "reflect"

	pgtype "github.com/jackc/pgx/v5/pgtype"
	gomock "go.uber.org/mock/gomock"
)

// Mockrepository is a mock of repository interface.
type Mockrepository struct {
	ctrl     *gomock.Controller
	recorder *MockrepositoryMockRecorder
	isgomock struct{}
}

// MockrepositoryMockRecorder is the mock recorder for Mockrepository.
type MockrepositoryMockRecorder struct {
	mock *Mockrepository
}

// NewMockrepository creates a new mock instance.
func NewMockrepository(ctrl *gomock.Controller) *Mockrepository {
	mock := &Mockrepository{ctrl: ctrl}
	mock.recorder = &MockrepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *Mockrepository) EXPECT() *MockrepositoryMockRecorder {
	return m.recorder
}

// FollowUser mocks base method.
func (m *Mockrepository) FollowUser(arg0 context.Context, arg1 postgres.FollowUserParams) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FollowUser", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// FollowUser indicates an expected call of FollowUser.
func (mr *MockrepositoryMockRecorder) FollowUser(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FollowUser", reflect.TypeOf((*Mockrepository)(nil).FollowUser), arg0, arg1)
}

// IsFollowing mocks base method.
func (m *Mockrepository) IsFollowing(arg0 context.Context, arg1 postgres.IsFollowingParams) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsFollowing", arg0, arg1)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// IsFollowing indicates an expected call of IsFollowing.
func (mr *MockrepositoryMockRecorder) IsFollowing(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsFollowing", reflect.TypeOf((*Mockrepository)(nil).IsFollowing), arg0, arg1)
}

// ListFolloweeIDsByFollowerID mocks base method.
func (m *Mockrepository) ListFolloweeIDsByFollowerID(arg0 context.Context, arg1 pgtype.UUID) ([]pgtype.UUID, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListFolloweeIDsByFollowerID", arg0, arg1)
	ret0, _ := ret[0].([]pgtype.UUID)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListFolloweeIDsByFollowerID indicates an expected call of ListFolloweeIDsByFollowerID.
func (mr *MockrepositoryMockRecorder) ListFolloweeIDsByFollowerID(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListFolloweeIDsByFollowerID", reflect.TypeOf((*Mockrepository)(nil).ListFolloweeIDsByFollowerID), arg0, arg1)
}

// ListFollowingIDs mocks base method.
func (m *Mockrepository) ListFollowingIDs(arg0 context.Context, arg1 postgres.ListFollowingIDsParams) ([]pgtype.UUID, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListFollowingIDs", arg0, arg1)
	ret0, _ := ret[0].([]pgtype.UUID)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListFollowingIDs indicates an expected call of ListFollowingIDs.
func (mr *MockrepositoryMockRecorder) ListFollowingIDs(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListFollowingIDs", reflect.TypeOf((*Mockrepository)(nil).ListFollowingIDs), arg0, arg1)
}

// UnfollowUser mocks base method.
func (m *Mockrepository) UnfollowUser(arg0 context.Context, arg1 postgres.UnfollowUserParams) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UnfollowUser", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// UnfollowUser indicates an expected call of UnfollowUser.
func (mr *MockrepositoryMockRecorder) UnfollowUser(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UnfollowUser", reflect.TypeOf((*Mockrepository)(nil).UnfollowUser), arg0, arg1)
}
