// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"conduit/internal/config"
	"conduit/internal/transport/http"
	"context"
)

// Injectors from wire.go:

//go:generate go tool wire
func initializeApplication(ctx context.Context, configPath string) (*application, func(), error) {
	configConfig, err := config.Load(configPath)
	if err != nil {
		return nil, nil, err
	}
	logger, err := provideLogger(configConfig)
	if err != nil {
		return nil, nil, err
	}
	v, cleanup, err := provideApplicationService(configConfig)
	if err != nil {
		return nil, nil, err
	}
	authMiddleware := provideAuthMiddleware(v)
	v2 := providePrometheusRegistry()
	metricsHTTP, err := provideHTTPMetrics(v2)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	panicReporter := providePanicReporter(logger)
	strictServerInterface := http.NewServer(v)
	handler, err := provideHTTPHandler(configConfig, authMiddleware, metricsHTTP, panicReporter, strictServerInterface, v, v2)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	mainApplication := newApplication(logger, handler)
	return mainApplication, func() {
		cleanup()
	}, nil
}
