// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"conduit/internal/config"
	"conduit/internal/service"
	"conduit/internal/transport/http"
	"conduit/internal/transport/middleware"
	"context"
)

// Injectors from wire.go:

//go:generate go tool wire
func initializeApplication(ctx context.Context, configPath string) (*application, func(), error) {
	configConfig, err := config.Load(configPath)
	if err != nil {
		return nil, nil, err
	}
	logger, err := provideLogger(configConfig)
	if err != nil {
		return nil, nil, err
	}
	pool, cleanup, err := provideDatabase(ctx, configConfig, logger)
	if err != nil {
		return nil, nil, err
	}
	registry := providePrometheusRegistry()
	metrics, err := provideRepositoryMetrics(registry)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	querier := provideQueries(pool, metrics)
	v := provideQueryDecorator(metrics)
	transactions := provideTransactions(pool, v)
	followService := provideFollowService(querier)
	userService := provideUserService(querier, followService, configConfig)
	tagService := provideTagService(querier)
	articletagService := provideArticleTagService(querier)
	favoriteService := provideFavoriteService(querier)
	articleService := provideArticleService(querier, transactions, userService, tagService, articletagService, favoriteService, followService)
	authService := provideAuthService(querier, transactions, configConfig)
	commentService := provideCommentService(querier, userService)
	serviceService := service.New(articleService, authService, commentService, tagService, userService)
	authMiddleware := middleware.NewAuthMiddleware(serviceService)
	httpMetrics, err := provideHTTPMetrics(registry)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	panicReporter := providePanicReporter(logger)
	strictServerInterface := http.NewServer(serviceService)
	handler, err := provideHTTPHandler(configConfig, logger, authMiddleware, httpMetrics, panicReporter, strictServerInterface, registry)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	mainApplication := newApplication(logger, handler)
	return mainApplication, func() {
		cleanup()
	}, nil
}
