// Code generated by gowrap. DO NOT EDIT.
// template: ../../wrap/prometheus.tpl
// gowrap: http://github.com/hexdigest/gowrap

package metrics

import (
	"context"
	"time"

	"github.com/jackc/pgx/v5/pgtype"

	_sourcePostgres "conduit/internal/gen/postgres"
)

// QuerierMetrics decorates every repository method with Prometheus metrics.
type QuerierMetrics struct {
	base    _sourcePostgres.Querier
	metrics *Repository
}

// NewQuerierMetrics wraps a repository without exposing query text or arguments
// as labels. The method name and result have bounded cardinality.
func NewQuerierMetrics(base _sourcePostgres.Querier, metrics *Repository) _sourcePostgres.Querier {
	return &QuerierMetrics{base: base, metrics: metrics}
}

// AttachTagsToArticle implements _sourcePostgres.Querier.
func (w *QuerierMetrics) AttachTagsToArticle(ctx context.Context, arg _sourcePostgres.AttachTagsToArticleParams) (err error) {
	started := time.Now()
	defer func() {
		w.metrics.observe("AttachTagsToArticle", started, err)
	}()
	return w.base.AttachTagsToArticle(ctx, arg)
}

// CountArticles implements _sourcePostgres.Querier.
func (w *QuerierMetrics) CountArticles(ctx context.Context, arg _sourcePostgres.CountArticlesParams) (i1 int64, err error) {
	started := time.Now()
	defer func() {
		w.metrics.observe("CountArticles", started, err)
	}()
	return w.base.CountArticles(ctx, arg)
}

// CountFavoritesByArticleIDs implements _sourcePostgres.Querier.
func (w *QuerierMetrics) CountFavoritesByArticleIDs(ctx context.Context, articleIds []pgtype.UUID) (ca1 []_sourcePostgres.CountFavoritesByArticleIDsRow, err error) {
	started := time.Now()
	defer func() {
		w.metrics.observe("CountFavoritesByArticleIDs", started, err)
	}()
	return w.base.CountFavoritesByArticleIDs(ctx, articleIds)
}

// CreateArticle implements _sourcePostgres.Querier.
func (w *QuerierMetrics) CreateArticle(ctx context.Context, arg _sourcePostgres.CreateArticleParams) (u1 pgtype.UUID, err error) {
	started := time.Now()
	defer func() {
		w.metrics.observe("CreateArticle", started, err)
	}()
	return w.base.CreateArticle(ctx, arg)
}

// CreateComment implements _sourcePostgres.Querier.
func (w *QuerierMetrics) CreateComment(ctx context.Context, arg _sourcePostgres.CreateCommentParams) (c2 _sourcePostgres.CreateCommentRow, err error) {
	started := time.Now()
	defer func() {
		w.metrics.observe("CreateComment", started, err)
	}()
	return w.base.CreateComment(ctx, arg)
}

// CreateSession implements _sourcePostgres.Querier.
func (w *QuerierMetrics) CreateSession(ctx context.Context, arg _sourcePostgres.CreateSessionParams) (err error) {
	started := time.Now()
	defer func() {
		w.metrics.observe("CreateSession", started, err)
	}()
	return w.base.CreateSession(ctx, arg)
}

// CreateUser implements _sourcePostgres.Querier.
func (w *QuerierMetrics) CreateUser(ctx context.Context, arg _sourcePostgres.CreateUserParams) (u1 _sourcePostgres.User, err error) {
	started := time.Now()
	defer func() {
		w.metrics.observe("CreateUser", started, err)
	}()
	return w.base.CreateUser(ctx, arg)
}

// DeleteArticleBySlugAndAuthorID implements _sourcePostgres.Querier.
func (w *QuerierMetrics) DeleteArticleBySlugAndAuthorID(ctx context.Context, arg _sourcePostgres.DeleteArticleBySlugAndAuthorIDParams) (i1 int64, err error) {
	started := time.Now()
	defer func() {
		w.metrics.observe("DeleteArticleBySlugAndAuthorID", started, err)
	}()
	return w.base.DeleteArticleBySlugAndAuthorID(ctx, arg)
}

// DeleteArticleTags implements _sourcePostgres.Querier.
func (w *QuerierMetrics) DeleteArticleTags(ctx context.Context, articleID pgtype.UUID) (err error) {
	started := time.Now()
	defer func() {
		w.metrics.observe("DeleteArticleTags", started, err)
	}()
	return w.base.DeleteArticleTags(ctx, articleID)
}

// DeleteCommentByIDAndArticleIDAndAuthorID implements _sourcePostgres.Querier.
func (w *QuerierMetrics) DeleteCommentByIDAndArticleIDAndAuthorID(ctx context.Context, arg _sourcePostgres.DeleteCommentByIDAndArticleIDAndAuthorIDParams) (i1 int64, err error) {
	started := time.Now()
	defer func() {
		w.metrics.observe("DeleteCommentByIDAndArticleIDAndAuthorID", started, err)
	}()
	return w.base.DeleteCommentByIDAndArticleIDAndAuthorID(ctx, arg)
}

// FavoriteArticle implements _sourcePostgres.Querier.
func (w *QuerierMetrics) FavoriteArticle(ctx context.Context, arg _sourcePostgres.FavoriteArticleParams) (err error) {
	started := time.Now()
	defer func() {
		w.metrics.observe("FavoriteArticle", started, err)
	}()
	return w.base.FavoriteArticle(ctx, arg)
}

// FollowUser implements _sourcePostgres.Querier.
func (w *QuerierMetrics) FollowUser(ctx context.Context, arg _sourcePostgres.FollowUserParams) (err error) {
	started := time.Now()
	defer func() {
		w.metrics.observe("FollowUser", started, err)
	}()
	return w.base.FollowUser(ctx, arg)
}

// GetArticleBySlug implements _sourcePostgres.Querier.
func (w *QuerierMetrics) GetArticleBySlug(ctx context.Context, slug string) (a1 _sourcePostgres.Article, err error) {
	started := time.Now()
	defer func() {
		w.metrics.observe("GetArticleBySlug", started, err)
	}()
	return w.base.GetArticleBySlug(ctx, slug)
}

// GetArticleIDBySlug implements _sourcePostgres.Querier.
func (w *QuerierMetrics) GetArticleIDBySlug(ctx context.Context, slug string) (u1 pgtype.UUID, err error) {
	started := time.Now()
	defer func() {
		w.metrics.observe("GetArticleIDBySlug", started, err)
	}()
	return w.base.GetArticleIDBySlug(ctx, slug)
}

// GetCommentAuthorIDByIDAndArticleID implements _sourcePostgres.Querier.
func (w *QuerierMetrics) GetCommentAuthorIDByIDAndArticleID(ctx context.Context, arg _sourcePostgres.GetCommentAuthorIDByIDAndArticleIDParams) (u1 pgtype.UUID, err error) {
	started := time.Now()
	defer func() {
		w.metrics.observe("GetCommentAuthorIDByIDAndArticleID", started, err)
	}()
	return w.base.GetCommentAuthorIDByIDAndArticleID(ctx, arg)
}

// GetSessionByUserIDAndJWTIDAndRefreshToken implements _sourcePostgres.Querier.
func (w *QuerierMetrics) GetSessionByUserIDAndJWTIDAndRefreshToken(ctx context.Context, arg _sourcePostgres.GetSessionByUserIDAndJWTIDAndRefreshTokenParams) (s1 _sourcePostgres.Session, err error) {
	started := time.Now()
	defer func() {
		w.metrics.observe("GetSessionByUserIDAndJWTIDAndRefreshToken", started, err)
	}()
	return w.base.GetSessionByUserIDAndJWTIDAndRefreshToken(ctx, arg)
}

// GetTagIDByName implements _sourcePostgres.Querier.
func (w *QuerierMetrics) GetTagIDByName(ctx context.Context, name string) (u1 pgtype.UUID, err error) {
	started := time.Now()
	defer func() {
		w.metrics.observe("GetTagIDByName", started, err)
	}()
	return w.base.GetTagIDByName(ctx, name)
}

// GetUserByEmail implements _sourcePostgres.Querier.
func (w *QuerierMetrics) GetUserByEmail(ctx context.Context, email string) (u1 _sourcePostgres.User, err error) {
	started := time.Now()
	defer func() {
		w.metrics.observe("GetUserByEmail", started, err)
	}()
	return w.base.GetUserByEmail(ctx, email)
}

// GetUserByID implements _sourcePostgres.Querier.
func (w *QuerierMetrics) GetUserByID(ctx context.Context, id pgtype.UUID) (u1 _sourcePostgres.User, err error) {
	started := time.Now()
	defer func() {
		w.metrics.observe("GetUserByID", started, err)
	}()
	return w.base.GetUserByID(ctx, id)
}

// GetUserByUsername implements _sourcePostgres.Querier.
func (w *QuerierMetrics) GetUserByUsername(ctx context.Context, username string) (u1 _sourcePostgres.User, err error) {
	started := time.Now()
	defer func() {
		w.metrics.observe("GetUserByUsername", started, err)
	}()
	return w.base.GetUserByUsername(ctx, username)
}

// GetUserIDByUsername implements _sourcePostgres.Querier.
func (w *QuerierMetrics) GetUserIDByUsername(ctx context.Context, username string) (u1 pgtype.UUID, err error) {
	started := time.Now()
	defer func() {
		w.metrics.observe("GetUserIDByUsername", started, err)
	}()
	return w.base.GetUserIDByUsername(ctx, username)
}

// IsFollowing implements _sourcePostgres.Querier.
func (w *QuerierMetrics) IsFollowing(ctx context.Context, arg _sourcePostgres.IsFollowingParams) (b1 bool, err error) {
	started := time.Now()
	defer func() {
		w.metrics.observe("IsFollowing", started, err)
	}()
	return w.base.IsFollowing(ctx, arg)
}

// ListArticleIDsByTagID implements _sourcePostgres.Querier.
func (w *QuerierMetrics) ListArticleIDsByTagID(ctx context.Context, tagID pgtype.UUID) (ua1 []pgtype.UUID, err error) {
	started := time.Now()
	defer func() {
		w.metrics.observe("ListArticleIDsByTagID", started, err)
	}()
	return w.base.ListArticleIDsByTagID(ctx, tagID)
}

// ListArticleTagRelationsByArticleIDs implements _sourcePostgres.Querier.
func (w *QuerierMetrics) ListArticleTagRelationsByArticleIDs(ctx context.Context, articleIds []pgtype.UUID) (la1 []_sourcePostgres.ListArticleTagRelationsByArticleIDsRow, err error) {
	started := time.Now()
	defer func() {
		w.metrics.observe("ListArticleTagRelationsByArticleIDs", started, err)
	}()
	return w.base.ListArticleTagRelationsByArticleIDs(ctx, articleIds)
}

// ListArticles implements _sourcePostgres.Querier.
func (w *QuerierMetrics) ListArticles(ctx context.Context, arg _sourcePostgres.ListArticlesParams) (aa1 []_sourcePostgres.Article, err error) {
	started := time.Now()
	defer func() {
		w.metrics.observe("ListArticles", started, err)
	}()
	return w.base.ListArticles(ctx, arg)
}

// ListCommentsByArticleID implements _sourcePostgres.Querier.
func (w *QuerierMetrics) ListCommentsByArticleID(ctx context.Context, articleID pgtype.UUID) (la1 []_sourcePostgres.ListCommentsByArticleIDRow, err error) {
	started := time.Now()
	defer func() {
		w.metrics.observe("ListCommentsByArticleID", started, err)
	}()
	return w.base.ListCommentsByArticleID(ctx, articleID)
}

// ListFavoriteArticleIDsByUserID implements _sourcePostgres.Querier.
func (w *QuerierMetrics) ListFavoriteArticleIDsByUserID(ctx context.Context, userID pgtype.UUID) (ua1 []pgtype.UUID, err error) {
	started := time.Now()
	defer func() {
		w.metrics.observe("ListFavoriteArticleIDsByUserID", started, err)
	}()
	return w.base.ListFavoriteArticleIDsByUserID(ctx, userID)
}

// ListFavoriteArticleIDsByUserIDAndArticleIDs implements _sourcePostgres.Querier.
func (w *QuerierMetrics) ListFavoriteArticleIDsByUserIDAndArticleIDs(ctx context.Context, arg _sourcePostgres.ListFavoriteArticleIDsByUserIDAndArticleIDsParams) (ua1 []pgtype.UUID, err error) {
	started := time.Now()
	defer func() {
		w.metrics.observe("ListFavoriteArticleIDsByUserIDAndArticleIDs", started, err)
	}()
	return w.base.ListFavoriteArticleIDsByUserIDAndArticleIDs(ctx, arg)
}

// ListFolloweeIDsByFollowerID implements _sourcePostgres.Querier.
func (w *QuerierMetrics) ListFolloweeIDsByFollowerID(ctx context.Context, followerID pgtype.UUID) (ua1 []pgtype.UUID, err error) {
	started := time.Now()
	defer func() {
		w.metrics.observe("ListFolloweeIDsByFollowerID", started, err)
	}()
	return w.base.ListFolloweeIDsByFollowerID(ctx, followerID)
}

// ListFollowingIDs implements _sourcePostgres.Querier.
func (w *QuerierMetrics) ListFollowingIDs(ctx context.Context, arg _sourcePostgres.ListFollowingIDsParams) (ua1 []pgtype.UUID, err error) {
	started := time.Now()
	defer func() {
		w.metrics.observe("ListFollowingIDs", started, err)
	}()
	return w.base.ListFollowingIDs(ctx, arg)
}

// ListProfilesByIDs implements _sourcePostgres.Querier.
func (w *QuerierMetrics) ListProfilesByIDs(ctx context.Context, ids []pgtype.UUID) (la1 []_sourcePostgres.ListProfilesByIDsRow, err error) {
	started := time.Now()
	defer func() {
		w.metrics.observe("ListProfilesByIDs", started, err)
	}()
	return w.base.ListProfilesByIDs(ctx, ids)
}

// ListTags implements _sourcePostgres.Querier.
func (w *QuerierMetrics) ListTags(ctx context.Context) (sa1 []string, err error) {
	started := time.Now()
	defer func() {
		w.metrics.observe("ListTags", started, err)
	}()
	return w.base.ListTags(ctx)
}

// ListTagsByIDs implements _sourcePostgres.Querier.
func (w *QuerierMetrics) ListTagsByIDs(ctx context.Context, ids []pgtype.UUID) (la1 []_sourcePostgres.ListTagsByIDsRow, err error) {
	started := time.Now()
	defer func() {
		w.metrics.observe("ListTagsByIDs", started, err)
	}()
	return w.base.ListTagsByIDs(ctx, ids)
}

// RotateSession implements _sourcePostgres.Querier.
func (w *QuerierMetrics) RotateSession(ctx context.Context, arg _sourcePostgres.RotateSessionParams) (i1 int64, err error) {
	started := time.Now()
	defer func() {
		w.metrics.observe("RotateSession", started, err)
	}()
	return w.base.RotateSession(ctx, arg)
}

// UnfavoriteArticle implements _sourcePostgres.Querier.
func (w *QuerierMetrics) UnfavoriteArticle(ctx context.Context, arg _sourcePostgres.UnfavoriteArticleParams) (err error) {
	started := time.Now()
	defer func() {
		w.metrics.observe("UnfavoriteArticle", started, err)
	}()
	return w.base.UnfavoriteArticle(ctx, arg)
}

// UnfollowUser implements _sourcePostgres.Querier.
func (w *QuerierMetrics) UnfollowUser(ctx context.Context, arg _sourcePostgres.UnfollowUserParams) (err error) {
	started := time.Now()
	defer func() {
		w.metrics.observe("UnfollowUser", started, err)
	}()
	return w.base.UnfollowUser(ctx, arg)
}

// UpdateArticle implements _sourcePostgres.Querier.
func (w *QuerierMetrics) UpdateArticle(ctx context.Context, arg _sourcePostgres.UpdateArticleParams) (u1 pgtype.UUID, err error) {
	started := time.Now()
	defer func() {
		w.metrics.observe("UpdateArticle", started, err)
	}()
	return w.base.UpdateArticle(ctx, arg)
}

// UpdateUser implements _sourcePostgres.Querier.
func (w *QuerierMetrics) UpdateUser(ctx context.Context, arg _sourcePostgres.UpdateUserParams) (u1 _sourcePostgres.User, err error) {
	started := time.Now()
	defer func() {
		w.metrics.observe("UpdateUser", started, err)
	}()
	return w.base.UpdateUser(ctx, arg)
}

// UpsertTags implements _sourcePostgres.Querier.
func (w *QuerierMetrics) UpsertTags(ctx context.Context, arg _sourcePostgres.UpsertTagsParams) (ta1 []_sourcePostgres.Tag, err error) {
	started := time.Now()
	defer func() {
		w.metrics.observe("UpsertTags", started, err)
	}()
	return w.base.UpsertTags(ctx, arg)
}
