// Code generated by MockGen. DO NOT EDIT.
// Source: conduit/internal/gen/grpc/conduit/posts/v1 (interfaces: PostsServiceClient)
//
// Generated by this command:
//
//	mockgen -destination=internal/transport/grpc/posts/mock_rpc_test.go -package=posts conduit/internal/gen/grpc/conduit/posts/v1 PostsServiceClient
//

// Package posts is a generated GoMock package.
package posts

import (
	postsv1 "conduit/internal/gen/grpc/conduit/posts/v1"
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
	grpc "google.golang.org/grpc"
)

// MockPostsServiceClient is a mock of PostsServiceClient interface.
type MockPostsServiceClient struct {
	ctrl     *gomock.Controller
	recorder *MockPostsServiceClientMockRecorder
	isgomock struct{}
}

// MockPostsServiceClientMockRecorder is the mock recorder for MockPostsServiceClient.
type MockPostsServiceClientMockRecorder struct {
	mock *MockPostsServiceClient
}

// NewMockPostsServiceClient creates a new mock instance.
func NewMockPostsServiceClient(ctrl *gomock.Controller) *MockPostsServiceClient {
	mock := &MockPostsServiceClient{ctrl: ctrl}
	mock.recorder = &MockPostsServiceClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPostsServiceClient) EXPECT() *MockPostsServiceClientMockRecorder {
	return m.recorder
}

// CreateArticle mocks base method.
func (m *MockPostsServiceClient) CreateArticle(ctx context.Context, in *postsv1.CreateArticleRequest, opts ...grpc.CallOption) (*postsv1.CreateArticleResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "CreateArticle", varargs...)
	ret0, _ := ret[0].(*postsv1.CreateArticleResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateArticle indicates an expected call of CreateArticle.
func (mr *MockPostsServiceClientMockRecorder) CreateArticle(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateArticle", reflect.TypeOf((*MockPostsServiceClient)(nil).CreateArticle), varargs...)
}

// DeleteArticle mocks base method.
func (m *MockPostsServiceClient) DeleteArticle(ctx context.Context, in *postsv1.DeleteArticleRequest, opts ...grpc.CallOption) (*postsv1.DeleteArticleResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "DeleteArticle", varargs...)
	ret0, _ := ret[0].(*postsv1.DeleteArticleResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteArticle indicates an expected call of DeleteArticle.
func (mr *MockPostsServiceClientMockRecorder) DeleteArticle(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteArticle", reflect.TypeOf((*MockPostsServiceClient)(nil).DeleteArticle), varargs...)
}

// FavoriteArticle mocks base method.
func (m *MockPostsServiceClient) FavoriteArticle(ctx context.Context, in *postsv1.FavoriteArticleRequest, opts ...grpc.CallOption) (*postsv1.FavoriteArticleResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "FavoriteArticle", varargs...)
	ret0, _ := ret[0].(*postsv1.FavoriteArticleResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FavoriteArticle indicates an expected call of FavoriteArticle.
func (mr *MockPostsServiceClientMockRecorder) FavoriteArticle(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FavoriteArticle", reflect.TypeOf((*MockPostsServiceClient)(nil).FavoriteArticle), varargs...)
}

// GetArticle mocks base method.
func (m *MockPostsServiceClient) GetArticle(ctx context.Context, in *postsv1.GetArticleRequest, opts ...grpc.CallOption) (*postsv1.GetArticleResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetArticle", varargs...)
	ret0, _ := ret[0].(*postsv1.GetArticleResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetArticle indicates an expected call of GetArticle.
func (mr *MockPostsServiceClientMockRecorder) GetArticle(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetArticle", reflect.TypeOf((*MockPostsServiceClient)(nil).GetArticle), varargs...)
}

// ListArticles mocks base method.
func (m *MockPostsServiceClient) ListArticles(ctx context.Context, in *postsv1.ListArticlesRequest, opts ...grpc.CallOption) (*postsv1.ListArticlesResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "ListArticles", varargs...)
	ret0, _ := ret[0].(*postsv1.ListArticlesResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListArticles indicates an expected call of ListArticles.
func (mr *MockPostsServiceClientMockRecorder) ListArticles(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListArticles", reflect.TypeOf((*MockPostsServiceClient)(nil).ListArticles), varargs...)
}

// ListFeed mocks base method.
func (m *MockPostsServiceClient) ListFeed(ctx context.Context, in *postsv1.ListFeedRequest, opts ...grpc.CallOption) (*postsv1.ListFeedResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "ListFeed", varargs...)
	ret0, _ := ret[0].(*postsv1.ListFeedResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListFeed indicates an expected call of ListFeed.
func (mr *MockPostsServiceClientMockRecorder) ListFeed(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListFeed", reflect.TypeOf((*MockPostsServiceClient)(nil).ListFeed), varargs...)
}

// ListTags mocks base method.
func (m *MockPostsServiceClient) ListTags(ctx context.Context, in *postsv1.ListTagsRequest, opts ...grpc.CallOption) (*postsv1.ListTagsResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "ListTags", varargs...)
	ret0, _ := ret[0].(*postsv1.ListTagsResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListTags indicates an expected call of ListTags.
func (mr *MockPostsServiceClientMockRecorder) ListTags(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListTags", reflect.TypeOf((*MockPostsServiceClient)(nil).ListTags), varargs...)
}

// ResolveArticleID mocks base method.
func (m *MockPostsServiceClient) ResolveArticleID(ctx context.Context, in *postsv1.ResolveArticleIDRequest, opts ...grpc.CallOption) (*postsv1.ResolveArticleIDResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "ResolveArticleID", varargs...)
	ret0, _ := ret[0].(*postsv1.ResolveArticleIDResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ResolveArticleID indicates an expected call of ResolveArticleID.
func (mr *MockPostsServiceClientMockRecorder) ResolveArticleID(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ResolveArticleID", reflect.TypeOf((*MockPostsServiceClient)(nil).ResolveArticleID), varargs...)
}

// UnfavoriteArticle mocks base method.
func (m *MockPostsServiceClient) UnfavoriteArticle(ctx context.Context, in *postsv1.UnfavoriteArticleRequest, opts ...grpc.CallOption) (*postsv1.UnfavoriteArticleResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "UnfavoriteArticle", varargs...)
	ret0, _ := ret[0].(*postsv1.UnfavoriteArticleResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UnfavoriteArticle indicates an expected call of UnfavoriteArticle.
func (mr *MockPostsServiceClientMockRecorder) UnfavoriteArticle(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UnfavoriteArticle", reflect.TypeOf((*MockPostsServiceClient)(nil).UnfavoriteArticle), varargs...)
}

// UpdateArticle mocks base method.
func (m *MockPostsServiceClient) UpdateArticle(ctx context.Context, in *postsv1.UpdateArticleRequest, opts ...grpc.CallOption) (*postsv1.UpdateArticleResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "UpdateArticle", varargs...)
	ret0, _ := ret[0].(*postsv1.UpdateArticleResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateArticle indicates an expected call of UpdateArticle.
func (mr *MockPostsServiceClientMockRecorder) UpdateArticle(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateArticle", reflect.TypeOf((*MockPostsServiceClient)(nil).UpdateArticle), varargs...)
}
