// Code generated by MockGen. DO NOT EDIT.
// Source: internal/transport/grpc/posts/client.go
//
// Generated by this command:
//
//	mockgen -destination=internal/transport/grpc/posts/mock_dependencies_test.go -package=posts -source=internal/transport/grpc/posts/client.go
//

// Package posts is a generated GoMock package.
package posts

import (
	models "conduit/internal/models"
	context "context"
	reflect "reflect"

	uuid "github.com/google/uuid"
	gomock "go.uber.org/mock/gomock"
)

// MockprofileReader is a mock of profileReader interface.
type MockprofileReader struct {
	ctrl     *gomock.Controller
	recorder *MockprofileReaderMockRecorder
	isgomock struct{}
}

// MockprofileReaderMockRecorder is the mock recorder for MockprofileReader.
type MockprofileReaderMockRecorder struct {
	mock *MockprofileReader
}

// NewMockprofileReader creates a new mock instance.
func NewMockprofileReader(ctrl *gomock.Controller) *MockprofileReader {
	mock := &MockprofileReader{ctrl: ctrl}
	mock.recorder = &MockprofileReaderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockprofileReader) EXPECT() *MockprofileReaderMockRecorder {
	return m.recorder
}

// IDByUsername mocks base method.
func (m *MockprofileReader) IDByUsername(arg0 context.Context, arg1 string) (uuid.UUID, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IDByUsername", arg0, arg1)
	ret0, _ := ret[0].(uuid.UUID)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// IDByUsername indicates an expected call of IDByUsername.
func (mr *MockprofileReaderMockRecorder) IDByUsername(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IDByUsername", reflect.TypeOf((*MockprofileReader)(nil).IDByUsername), arg0, arg1)
}

// ProfilesByIDs mocks base method.
func (m *MockprofileReader) ProfilesByIDs(arg0 context.Context, arg1 []uuid.UUID) (map[uuid.UUID]models.Profile, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ProfilesByIDs", arg0, arg1)
	ret0, _ := ret[0].(map[uuid.UUID]models.Profile)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ProfilesByIDs indicates an expected call of ProfilesByIDs.
func (mr *MockprofileReaderMockRecorder) ProfilesByIDs(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ProfilesByIDs", reflect.TypeOf((*MockprofileReader)(nil).ProfilesByIDs), arg0, arg1)
}

// MocksubscriptionReader is a mock of subscriptionReader interface.
type MocksubscriptionReader struct {
	ctrl     *gomock.Controller
	recorder *MocksubscriptionReaderMockRecorder
	isgomock struct{}
}

// MocksubscriptionReaderMockRecorder is the mock recorder for MocksubscriptionReader.
type MocksubscriptionReaderMockRecorder struct {
	mock *MocksubscriptionReader
}

// NewMocksubscriptionReader creates a new mock instance.
func NewMocksubscriptionReader(ctrl *gomock.Controller) *MocksubscriptionReader {
	mock := &MocksubscriptionReader{ctrl: ctrl}
	mock.recorder = &MocksubscriptionReaderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MocksubscriptionReader) EXPECT() *MocksubscriptionReaderMockRecorder {
	return m.recorder
}

// FolloweeIDs mocks base method.
func (m *MocksubscriptionReader) FolloweeIDs(arg0 context.Context, arg1 uuid.UUID) ([]uuid.UUID, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FolloweeIDs", arg0, arg1)
	ret0, _ := ret[0].([]uuid.UUID)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FolloweeIDs indicates an expected call of FolloweeIDs.
func (mr *MocksubscriptionReaderMockRecorder) FolloweeIDs(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FolloweeIDs", reflect.TypeOf((*MocksubscriptionReader)(nil).FolloweeIDs), arg0, arg1)
}

// FollowingIDs mocks base method.
func (m *MocksubscriptionReader) FollowingIDs(arg0 context.Context, arg1 uuid.UUID, arg2 []uuid.UUID) (map[uuid.UUID]struct{}, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FollowingIDs", arg0, arg1, arg2)
	ret0, _ := ret[0].(map[uuid.UUID]struct{})
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FollowingIDs indicates an expected call of FollowingIDs.
func (mr *MocksubscriptionReaderMockRecorder) FollowingIDs(arg0, arg1, arg2 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FollowingIDs", reflect.TypeOf((*MocksubscriptionReader)(nil).FollowingIDs), arg0, arg1, arg2)
}
